/* soapUnimapSoapXmlBindingService.cpp
   Generated by gSOAP 2.7.16 from unimap_service.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#include "soapUnimapSoapXmlBindingService.h"

UnimapSoapXmlBindingService::UnimapSoapXmlBindingService()
{	UnimapSoapXmlBindingService_init(SOAP_IO_DEFAULT, SOAP_IO_DEFAULT);
}

UnimapSoapXmlBindingService::UnimapSoapXmlBindingService(const struct soap &_soap) :soap(_soap)
{ }

UnimapSoapXmlBindingService::UnimapSoapXmlBindingService(soap_mode iomode)
{	UnimapSoapXmlBindingService_init(iomode, iomode);
}

UnimapSoapXmlBindingService::UnimapSoapXmlBindingService(soap_mode imode, soap_mode omode)
{	UnimapSoapXmlBindingService_init(imode, omode);
}

UnimapSoapXmlBindingService::~UnimapSoapXmlBindingService()
{ }

void UnimapSoapXmlBindingService::UnimapSoapXmlBindingService_init(soap_mode imode, soap_mode omode)
{	soap_imode(this, imode);
	soap_omode(this, omode);
	static const struct Namespace namespaces[] =
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns", "urn:UnimapSoapXml", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	this->namespaces = namespaces;
};

void UnimapSoapXmlBindingService::destroy()
{	soap_destroy(this);
	soap_end(this);
}

UnimapSoapXmlBindingService *UnimapSoapXmlBindingService::copy()
{	UnimapSoapXmlBindingService *dup = SOAP_NEW_COPY(UnimapSoapXmlBindingService(*(struct soap*)this));
	return dup;
}

int UnimapSoapXmlBindingService::soap_close_socket()
{	return soap_closesock(this);
}

int UnimapSoapXmlBindingService::soap_senderfault(const char *string, const char *detailXML)
{	return ::soap_sender_fault(this, string, detailXML);
}

int UnimapSoapXmlBindingService::soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_sender_fault_subcode(this, subcodeQName, string, detailXML);
}

int UnimapSoapXmlBindingService::soap_receiverfault(const char *string, const char *detailXML)
{	return ::soap_receiver_fault(this, string, detailXML);
}

int UnimapSoapXmlBindingService::soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML)
{	return ::soap_receiver_fault_subcode(this, subcodeQName, string, detailXML);
}

void UnimapSoapXmlBindingService::soap_print_fault(FILE *fd)
{	::soap_print_fault(this, fd);
}

#ifndef WITH_LEAN
void UnimapSoapXmlBindingService::soap_stream_fault(std::ostream& os)
{	::soap_stream_fault(this, os);
}

char *UnimapSoapXmlBindingService::soap_sprint_fault(char *buf, size_t len)
{	return ::soap_sprint_fault(this, buf, len);
}
#endif

void UnimapSoapXmlBindingService::soap_noheader()
{	header = NULL;
}

int UnimapSoapXmlBindingService::run(int port)
{	if (soap_valid_socket(bind(NULL, port, 100)))
	{	for (;;)
		{	if (!soap_valid_socket(accept()))
				return this->error;
			(void)serve();
			soap_destroy(this);
			soap_end(this);
		}
	}
	else
		return this->error;
	return SOAP_OK;
}

SOAP_SOCKET UnimapSoapXmlBindingService::bind(const char *host, int port, int backlog)
{	return soap_bind(this, host, port, backlog);
}

SOAP_SOCKET UnimapSoapXmlBindingService::accept()
{	return soap_accept(this);
}

int UnimapSoapXmlBindingService::serve()
{
#ifndef WITH_FASTCGI
	unsigned int k = this->max_keep_alive;
#endif
	do
	{	soap_begin(this);
#ifdef WITH_FASTCGI
		if (FCGI_Accept() < 0)
		{
			this->error = SOAP_EOF;
			return soap_send_fault(this);
		}
#endif

		soap_begin(this);

#ifndef WITH_FASTCGI
		if (this->max_keep_alive > 0 && !--k)
			this->keep_alive = 0;
#endif

		if (soap_begin_recv(this))
		{	if (this->error < SOAP_STOP)
			{
#ifdef WITH_FASTCGI
				soap_send_fault(this);
#else 
				return soap_send_fault(this);
#endif
			}
			soap_closesock(this);

			continue;
		}

		if (soap_envelope_begin_in(this)
		 || soap_recv_header(this)
		 || soap_body_begin_in(this)
		 || dispatch() || (this->fserveloop && this->fserveloop(this)))
		{
#ifdef WITH_FASTCGI
			soap_send_fault(this);
#else
			return soap_send_fault(this);
#endif
		}

#ifdef WITH_FASTCGI
		soap_destroy(this);
		soap_end(this);
	} while (1);
#else
	} while (this->keep_alive);
#endif
	return SOAP_OK;
}

static int serve___ns__ImageSolve(UnimapSoapXmlBindingService*);
static int serve___ns__ScopePositionSet(UnimapSoapXmlBindingService*);
static int serve___ns__ScopePositionGet(UnimapSoapXmlBindingService*);
static int serve___ns__CameraImageTake(UnimapSoapXmlBindingService*);
static int serve___ns__ScopeFocusAdjust(UnimapSoapXmlBindingService*);

int UnimapSoapXmlBindingService::dispatch()
{	if (soap_peek_element(this))
		return this->error;
	if (!soap_match_tag(this, this->tag, "ns:ImageSolveRequest"))
		return serve___ns__ImageSolve(this);
	if (!soap_match_tag(this, this->tag, "input"))
		return serve___ns__ScopePositionSet(this);
	if (!soap_match_tag(this, this->tag, "input"))
		return serve___ns__ScopePositionGet(this);
	if (!soap_match_tag(this, this->tag, "input"))
		return serve___ns__CameraImageTake(this);
	if (!soap_match_tag(this, this->tag, "input"))
		return serve___ns__ScopeFocusAdjust(this);
	return this->error = SOAP_NO_METHOD;
}

static int serve___ns__ImageSolve(UnimapSoapXmlBindingService *soap)
{	struct __ns__ImageSolve soap_tmp___ns__ImageSolve;
	ns__ImageSolveResponseType ns__ImageSolveResponse;
	ns__ImageSolveResponse.soap_default(soap);
	soap_default___ns__ImageSolve(soap, &soap_tmp___ns__ImageSolve);
	soap->encodingStyle = NULL;
	if (!soap_get___ns__ImageSolve(soap, &soap_tmp___ns__ImageSolve, "-ns:ImageSolve", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->ImageSolve(soap_tmp___ns__ImageSolve.ns__ImageSolveRequest, &ns__ImageSolveResponse);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	ns__ImageSolveResponse.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || ns__ImageSolveResponse.soap_put(soap, "ns:ImageSolveResponse", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || ns__ImageSolveResponse.soap_put(soap, "ns:ImageSolveResponse", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns__ScopePositionSet(UnimapSoapXmlBindingService *soap)
{	struct __ns__ScopePositionSet soap_tmp___ns__ScopePositionSet;
	ns__ScopePositionSetResponseType result;
	result.soap_default(soap);
	soap_default___ns__ScopePositionSet(soap, &soap_tmp___ns__ScopePositionSet);
	soap->encodingStyle = NULL;
	if (!soap_get___ns__ScopePositionSet(soap, &soap_tmp___ns__ScopePositionSet, "-ns:ScopePositionSet", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->ScopePositionSet(soap_tmp___ns__ScopePositionSet.input, &result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	result.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || result.soap_put(soap, "ns:ScopePositionSetResponseType", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || result.soap_put(soap, "ns:ScopePositionSetResponseType", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns__ScopePositionGet(UnimapSoapXmlBindingService *soap)
{	struct __ns__ScopePositionGet soap_tmp___ns__ScopePositionGet;
	ns__ScopePositionGetResponseType result;
	result.soap_default(soap);
	soap_default___ns__ScopePositionGet(soap, &soap_tmp___ns__ScopePositionGet);
	soap->encodingStyle = NULL;
	if (!soap_get___ns__ScopePositionGet(soap, &soap_tmp___ns__ScopePositionGet, "-ns:ScopePositionGet", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->ScopePositionGet(soap_tmp___ns__ScopePositionGet.input, &result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	result.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || result.soap_put(soap, "ns:ScopePositionGetResponseType", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || result.soap_put(soap, "ns:ScopePositionGetResponseType", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns__CameraImageTake(UnimapSoapXmlBindingService *soap)
{	struct __ns__CameraImageTake soap_tmp___ns__CameraImageTake;
	ns__CameraImageTakeResponseType result;
	result.soap_default(soap);
	soap_default___ns__CameraImageTake(soap, &soap_tmp___ns__CameraImageTake);
	soap->encodingStyle = NULL;
	if (!soap_get___ns__CameraImageTake(soap, &soap_tmp___ns__CameraImageTake, "-ns:CameraImageTake", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->CameraImageTake(soap_tmp___ns__CameraImageTake.input, &result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	result.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || result.soap_put(soap, "ns:CameraImageTakeResponseType", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || result.soap_put(soap, "ns:CameraImageTakeResponseType", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}

static int serve___ns__ScopeFocusAdjust(UnimapSoapXmlBindingService *soap)
{	struct __ns__ScopeFocusAdjust soap_tmp___ns__ScopeFocusAdjust;
	ns__ScopeFocusAdjustResponseType result;
	result.soap_default(soap);
	soap_default___ns__ScopeFocusAdjust(soap, &soap_tmp___ns__ScopeFocusAdjust);
	soap->encodingStyle = NULL;
	if (!soap_get___ns__ScopeFocusAdjust(soap, &soap_tmp___ns__ScopeFocusAdjust, "-ns:ScopeFocusAdjust", NULL))
		return soap->error;
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap->error;
	soap->error = soap->ScopeFocusAdjust(soap_tmp___ns__ScopeFocusAdjust.input, &result);
	if (soap->error)
		return soap->error;
	soap_serializeheader(soap);
	result.soap_serialize(soap);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || result.soap_put(soap, "ns:ScopeFocusAdjustResponseType", "")
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	};
	if (soap_end_count(soap)
	 || soap_response(soap, SOAP_OK)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || result.soap_put(soap, "ns:ScopeFocusAdjustResponseType", "")
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap->error;
	return soap_closesock(soap);
}
/* End of server object code */
