/* soapH.h
   Generated by gSOAP 2.7.16 from unimap_service.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#define soap_write_byte(soap, data) ( soap_begin_send(soap) || soap_put_byte(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef SOAP_TYPE_short
#define SOAP_TYPE_short (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_short(struct soap*, short *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_short(struct soap*, const char*, int, const short *, const char*);
SOAP_FMAC3 short * SOAP_FMAC4 soap_in_short(struct soap*, const char*, short *, const char*);

#define soap_write_short(soap, data) ( soap_begin_send(soap) || soap_put_short(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_short(struct soap*, const short *, const char*, const char*);

#define soap_read_short(soap, data) ( soap_begin_recv(soap) || !soap_get_short(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 short * SOAP_FMAC4 soap_get_short(struct soap*, short *, const char*, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#define soap_write_int(soap, data) ( soap_begin_send(soap) || soap_put_int(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef SOAP_TYPE_double
#define SOAP_TYPE_double (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_double(struct soap*, double *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_double(struct soap*, const char*, int, const double *, const char*);
SOAP_FMAC3 double * SOAP_FMAC4 soap_in_double(struct soap*, const char*, double *, const char*);

#define soap_write_double(soap, data) ( soap_begin_send(soap) || soap_put_double(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_double(struct soap*, const double *, const char*, const char*);

#define soap_read_double(soap, data) ( soap_begin_recv(soap) || !soap_get_double(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 double * SOAP_FMAC4 soap_get_double(struct soap*, double *, const char*, const char*);

#ifndef SOAP_TYPE_ns__ScopeFocusAdjustResponseType
#define SOAP_TYPE_ns__ScopeFocusAdjustResponseType (22)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ScopeFocusAdjustResponseType(struct soap*, const char*, int, const ns__ScopeFocusAdjustResponseType *, const char*);
SOAP_FMAC3 ns__ScopeFocusAdjustResponseType * SOAP_FMAC4 soap_in_ns__ScopeFocusAdjustResponseType(struct soap*, const char*, ns__ScopeFocusAdjustResponseType *, const char*);

#define soap_write_ns__ScopeFocusAdjustResponseType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__ScopeFocusAdjustResponseType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ScopeFocusAdjustResponseType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopeFocusAdjustResponseType * SOAP_FMAC4 soap_get_ns__ScopeFocusAdjustResponseType(struct soap*, ns__ScopeFocusAdjustResponseType *, const char*, const char*);

#define soap_new_ns__ScopeFocusAdjustResponseType(soap, n) soap_instantiate_ns__ScopeFocusAdjustResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__ScopeFocusAdjustResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__ScopeFocusAdjustResponseType * SOAP_FMAC2 soap_instantiate_ns__ScopeFocusAdjustResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ScopeFocusAdjustResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__ScopeFocusAdjustRequestType
#define SOAP_TYPE_ns__ScopeFocusAdjustRequestType (21)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ScopeFocusAdjustRequestType(struct soap*, const char*, int, const ns__ScopeFocusAdjustRequestType *, const char*);
SOAP_FMAC3 ns__ScopeFocusAdjustRequestType * SOAP_FMAC4 soap_in_ns__ScopeFocusAdjustRequestType(struct soap*, const char*, ns__ScopeFocusAdjustRequestType *, const char*);

#define soap_write_ns__ScopeFocusAdjustRequestType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__ScopeFocusAdjustRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ScopeFocusAdjustRequestType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopeFocusAdjustRequestType * SOAP_FMAC4 soap_get_ns__ScopeFocusAdjustRequestType(struct soap*, ns__ScopeFocusAdjustRequestType *, const char*, const char*);

#define soap_new_ns__ScopeFocusAdjustRequestType(soap, n) soap_instantiate_ns__ScopeFocusAdjustRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__ScopeFocusAdjustRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__ScopeFocusAdjustRequestType * SOAP_FMAC2 soap_instantiate_ns__ScopeFocusAdjustRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ScopeFocusAdjustRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__CameraImageTakeResponseType
#define SOAP_TYPE_ns__CameraImageTakeResponseType (20)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__CameraImageTakeResponseType(struct soap*, const char*, int, const ns__CameraImageTakeResponseType *, const char*);
SOAP_FMAC3 ns__CameraImageTakeResponseType * SOAP_FMAC4 soap_in_ns__CameraImageTakeResponseType(struct soap*, const char*, ns__CameraImageTakeResponseType *, const char*);

#define soap_write_ns__CameraImageTakeResponseType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__CameraImageTakeResponseType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__CameraImageTakeResponseType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__CameraImageTakeResponseType * SOAP_FMAC4 soap_get_ns__CameraImageTakeResponseType(struct soap*, ns__CameraImageTakeResponseType *, const char*, const char*);

#define soap_new_ns__CameraImageTakeResponseType(soap, n) soap_instantiate_ns__CameraImageTakeResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__CameraImageTakeResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__CameraImageTakeResponseType * SOAP_FMAC2 soap_instantiate_ns__CameraImageTakeResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__CameraImageTakeResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__CameraImageTakeRequestType
#define SOAP_TYPE_ns__CameraImageTakeRequestType (19)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__CameraImageTakeRequestType(struct soap*, const char*, int, const ns__CameraImageTakeRequestType *, const char*);
SOAP_FMAC3 ns__CameraImageTakeRequestType * SOAP_FMAC4 soap_in_ns__CameraImageTakeRequestType(struct soap*, const char*, ns__CameraImageTakeRequestType *, const char*);

#define soap_write_ns__CameraImageTakeRequestType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__CameraImageTakeRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__CameraImageTakeRequestType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__CameraImageTakeRequestType * SOAP_FMAC4 soap_get_ns__CameraImageTakeRequestType(struct soap*, ns__CameraImageTakeRequestType *, const char*, const char*);

#define soap_new_ns__CameraImageTakeRequestType(soap, n) soap_instantiate_ns__CameraImageTakeRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__CameraImageTakeRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__CameraImageTakeRequestType * SOAP_FMAC2 soap_instantiate_ns__CameraImageTakeRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__CameraImageTakeRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__ScopePositionGetResponseType
#define SOAP_TYPE_ns__ScopePositionGetResponseType (18)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ScopePositionGetResponseType(struct soap*, const char*, int, const ns__ScopePositionGetResponseType *, const char*);
SOAP_FMAC3 ns__ScopePositionGetResponseType * SOAP_FMAC4 soap_in_ns__ScopePositionGetResponseType(struct soap*, const char*, ns__ScopePositionGetResponseType *, const char*);

#define soap_write_ns__ScopePositionGetResponseType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__ScopePositionGetResponseType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ScopePositionGetResponseType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopePositionGetResponseType * SOAP_FMAC4 soap_get_ns__ScopePositionGetResponseType(struct soap*, ns__ScopePositionGetResponseType *, const char*, const char*);

#define soap_new_ns__ScopePositionGetResponseType(soap, n) soap_instantiate_ns__ScopePositionGetResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__ScopePositionGetResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__ScopePositionGetResponseType * SOAP_FMAC2 soap_instantiate_ns__ScopePositionGetResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ScopePositionGetResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__ScopePositionGetRequestType
#define SOAP_TYPE_ns__ScopePositionGetRequestType (17)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ScopePositionGetRequestType(struct soap*, const char*, int, const ns__ScopePositionGetRequestType *, const char*);
SOAP_FMAC3 ns__ScopePositionGetRequestType * SOAP_FMAC4 soap_in_ns__ScopePositionGetRequestType(struct soap*, const char*, ns__ScopePositionGetRequestType *, const char*);

#define soap_write_ns__ScopePositionGetRequestType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__ScopePositionGetRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ScopePositionGetRequestType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopePositionGetRequestType * SOAP_FMAC4 soap_get_ns__ScopePositionGetRequestType(struct soap*, ns__ScopePositionGetRequestType *, const char*, const char*);

#define soap_new_ns__ScopePositionGetRequestType(soap, n) soap_instantiate_ns__ScopePositionGetRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__ScopePositionGetRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__ScopePositionGetRequestType * SOAP_FMAC2 soap_instantiate_ns__ScopePositionGetRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ScopePositionGetRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__ScopePositionSetResponseType
#define SOAP_TYPE_ns__ScopePositionSetResponseType (16)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ScopePositionSetResponseType(struct soap*, const char*, int, const ns__ScopePositionSetResponseType *, const char*);
SOAP_FMAC3 ns__ScopePositionSetResponseType * SOAP_FMAC4 soap_in_ns__ScopePositionSetResponseType(struct soap*, const char*, ns__ScopePositionSetResponseType *, const char*);

#define soap_write_ns__ScopePositionSetResponseType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__ScopePositionSetResponseType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ScopePositionSetResponseType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopePositionSetResponseType * SOAP_FMAC4 soap_get_ns__ScopePositionSetResponseType(struct soap*, ns__ScopePositionSetResponseType *, const char*, const char*);

#define soap_new_ns__ScopePositionSetResponseType(soap, n) soap_instantiate_ns__ScopePositionSetResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__ScopePositionSetResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__ScopePositionSetResponseType * SOAP_FMAC2 soap_instantiate_ns__ScopePositionSetResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ScopePositionSetResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__ScopePositionSetRequestType
#define SOAP_TYPE_ns__ScopePositionSetRequestType (15)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ScopePositionSetRequestType(struct soap*, const char*, int, const ns__ScopePositionSetRequestType *, const char*);
SOAP_FMAC3 ns__ScopePositionSetRequestType * SOAP_FMAC4 soap_in_ns__ScopePositionSetRequestType(struct soap*, const char*, ns__ScopePositionSetRequestType *, const char*);

#define soap_write_ns__ScopePositionSetRequestType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__ScopePositionSetRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ScopePositionSetRequestType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopePositionSetRequestType * SOAP_FMAC4 soap_get_ns__ScopePositionSetRequestType(struct soap*, ns__ScopePositionSetRequestType *, const char*, const char*);

#define soap_new_ns__ScopePositionSetRequestType(soap, n) soap_instantiate_ns__ScopePositionSetRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__ScopePositionSetRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__ScopePositionSetRequestType * SOAP_FMAC2 soap_instantiate_ns__ScopePositionSetRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ScopePositionSetRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__ImageSolveResponseType
#define SOAP_TYPE_ns__ImageSolveResponseType (14)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ImageSolveResponseType(struct soap*, const char*, int, const ns__ImageSolveResponseType *, const char*);
SOAP_FMAC3 ns__ImageSolveResponseType * SOAP_FMAC4 soap_in_ns__ImageSolveResponseType(struct soap*, const char*, ns__ImageSolveResponseType *, const char*);

#define soap_write_ns__ImageSolveResponseType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__ImageSolveResponseType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ImageSolveResponseType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ImageSolveResponseType * SOAP_FMAC4 soap_get_ns__ImageSolveResponseType(struct soap*, ns__ImageSolveResponseType *, const char*, const char*);

#define soap_new_ns__ImageSolveResponseType(soap, n) soap_instantiate_ns__ImageSolveResponseType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__ImageSolveResponseType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__ImageSolveResponseType * SOAP_FMAC2 soap_instantiate_ns__ImageSolveResponseType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ImageSolveResponseType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__ImageSolveRequestType
#define SOAP_TYPE_ns__ImageSolveRequestType (13)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ImageSolveRequestType(struct soap*, const char*, int, const ns__ImageSolveRequestType *, const char*);
SOAP_FMAC3 ns__ImageSolveRequestType * SOAP_FMAC4 soap_in_ns__ImageSolveRequestType(struct soap*, const char*, ns__ImageSolveRequestType *, const char*);

#define soap_write_ns__ImageSolveRequestType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__ImageSolveRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ImageSolveRequestType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ImageSolveRequestType * SOAP_FMAC4 soap_get_ns__ImageSolveRequestType(struct soap*, ns__ImageSolveRequestType *, const char*, const char*);

#define soap_new_ns__ImageSolveRequestType(soap, n) soap_instantiate_ns__ImageSolveRequestType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__ImageSolveRequestType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__ImageSolveRequestType * SOAP_FMAC2 soap_instantiate_ns__ImageSolveRequestType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ImageSolveRequestType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__ImgObjDetectedType
#define SOAP_TYPE_ns__ImgObjDetectedType (12)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ImgObjDetectedType(struct soap*, const char*, int, const ns__ImgObjDetectedType *, const char*);
SOAP_FMAC3 ns__ImgObjDetectedType * SOAP_FMAC4 soap_in_ns__ImgObjDetectedType(struct soap*, const char*, ns__ImgObjDetectedType *, const char*);

#define soap_write_ns__ImgObjDetectedType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__ImgObjDetectedType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ImgObjDetectedType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ImgObjDetectedType * SOAP_FMAC4 soap_get_ns__ImgObjDetectedType(struct soap*, ns__ImgObjDetectedType *, const char*, const char*);

#define soap_new_ns__ImgObjDetectedType(soap, n) soap_instantiate_ns__ImgObjDetectedType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__ImgObjDetectedType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__ImgObjDetectedType * SOAP_FMAC2 soap_instantiate_ns__ImgObjDetectedType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ImgObjDetectedType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__ImgDataHeaderType
#define SOAP_TYPE_ns__ImgDataHeaderType (11)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ImgDataHeaderType(struct soap*, const char*, int, const ns__ImgDataHeaderType *, const char*);
SOAP_FMAC3 ns__ImgDataHeaderType * SOAP_FMAC4 soap_in_ns__ImgDataHeaderType(struct soap*, const char*, ns__ImgDataHeaderType *, const char*);

#define soap_write_ns__ImgDataHeaderType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__ImgDataHeaderType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ImgDataHeaderType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ImgDataHeaderType * SOAP_FMAC4 soap_get_ns__ImgDataHeaderType(struct soap*, ns__ImgDataHeaderType *, const char*, const char*);

#define soap_new_ns__ImgDataHeaderType(soap, n) soap_instantiate_ns__ImgDataHeaderType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__ImgDataHeaderType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__ImgDataHeaderType * SOAP_FMAC2 soap_instantiate_ns__ImgDataHeaderType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ImgDataHeaderType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__ResponseStatusType
#define SOAP_TYPE_ns__ResponseStatusType (10)
#endif

SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__ResponseStatusType(struct soap*, const char*, int, const ns__ResponseStatusType *, const char*);
SOAP_FMAC3 ns__ResponseStatusType * SOAP_FMAC4 soap_in_ns__ResponseStatusType(struct soap*, const char*, ns__ResponseStatusType *, const char*);

#define soap_write_ns__ResponseStatusType(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


#define soap_read_ns__ResponseStatusType(soap, data) ( soap_begin_recv(soap) || !soap_get_ns__ResponseStatusType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ResponseStatusType * SOAP_FMAC4 soap_get_ns__ResponseStatusType(struct soap*, ns__ResponseStatusType *, const char*, const char*);

#define soap_new_ns__ResponseStatusType(soap, n) soap_instantiate_ns__ResponseStatusType(soap, n, NULL, NULL, NULL)


#define soap_delete_ns__ResponseStatusType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 ns__ResponseStatusType * SOAP_FMAC2 soap_instantiate_ns__ResponseStatusType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__ResponseStatusType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__integer
#define SOAP_TYPE_xsd__integer (9)
#endif

#define soap_default_xsd__integer(soap, a) soap_default_std__string(soap, a)


#define soap_serialize_xsd__integer(soap, a) soap_serialize_std__string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__integer(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_xsd__integer(struct soap*, const char*, std::string*, const char*);

#define soap_write_xsd__integer(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__integer(struct soap*, const std::string *, const char*, const char*);

#define soap_read_xsd__integer(soap, data) ( soap_begin_recv(soap) || !soap_get_xsd__integer(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_xsd__integer(struct soap*, std::string *, const char*, const char*);

#define soap_new_xsd__integer(soap, n) soap_instantiate_xsd__integer(soap, n, NULL, NULL, NULL)


#define soap_delete_xsd__integer(soap, p) soap_delete(soap, p)


#define soap_instantiate_xsd__integer soap_instantiate_std__string


#define soap_copy_xsd__integer soap_copy_std__string

#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

#define soap_write_std__string(soap, data) ( soap_begin_send(soap) || ((data)->soap_serialize(soap), 0) || (data)->soap_put(soap, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#define soap_new_std__string(soap, n) soap_instantiate_std__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Fault(soap, data), 0) || soap_put_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#define soap_new_SOAP_ENV__Fault(soap, n) soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Fault(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Reason(soap, data), 0) || soap_put_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#define soap_new_SOAP_ENV__Reason(soap, n) soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Reason(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Detail(soap, data), 0) || soap_put_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#define soap_new_SOAP_ENV__Detail(soap, n) soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Detail(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Code(soap, data), 0) || soap_put_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#define soap_new_SOAP_ENV__Code(soap, n) soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Code(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin_send(soap) || (soap_serialize_SOAP_ENV__Header(soap, data), 0) || soap_put_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#define soap_new_SOAP_ENV__Header(soap, n) soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL)


#define soap_delete_SOAP_ENV__Header(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE___ns__ScopeFocusAdjust
#define SOAP_TYPE___ns__ScopeFocusAdjust (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns__ScopeFocusAdjust(struct soap*, struct __ns__ScopeFocusAdjust *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns__ScopeFocusAdjust(struct soap*, const struct __ns__ScopeFocusAdjust *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns__ScopeFocusAdjust(struct soap*, const char*, int, const struct __ns__ScopeFocusAdjust *, const char*);
SOAP_FMAC3 struct __ns__ScopeFocusAdjust * SOAP_FMAC4 soap_in___ns__ScopeFocusAdjust(struct soap*, const char*, struct __ns__ScopeFocusAdjust *, const char*);

#define soap_write___ns__ScopeFocusAdjust(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns__ScopeFocusAdjust(soap, data), 0) || soap_put___ns__ScopeFocusAdjust(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns__ScopeFocusAdjust(struct soap*, const struct __ns__ScopeFocusAdjust *, const char*, const char*);

#define soap_read___ns__ScopeFocusAdjust(soap, data) ( soap_begin_recv(soap) || !soap_get___ns__ScopeFocusAdjust(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns__ScopeFocusAdjust * SOAP_FMAC4 soap_get___ns__ScopeFocusAdjust(struct soap*, struct __ns__ScopeFocusAdjust *, const char*, const char*);

#define soap_new___ns__ScopeFocusAdjust(soap, n) soap_instantiate___ns__ScopeFocusAdjust(soap, n, NULL, NULL, NULL)


#define soap_delete___ns__ScopeFocusAdjust(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns__ScopeFocusAdjust * SOAP_FMAC2 soap_instantiate___ns__ScopeFocusAdjust(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns__ScopeFocusAdjust(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns__CameraImageTake
#define SOAP_TYPE___ns__CameraImageTake (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns__CameraImageTake(struct soap*, struct __ns__CameraImageTake *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns__CameraImageTake(struct soap*, const struct __ns__CameraImageTake *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns__CameraImageTake(struct soap*, const char*, int, const struct __ns__CameraImageTake *, const char*);
SOAP_FMAC3 struct __ns__CameraImageTake * SOAP_FMAC4 soap_in___ns__CameraImageTake(struct soap*, const char*, struct __ns__CameraImageTake *, const char*);

#define soap_write___ns__CameraImageTake(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns__CameraImageTake(soap, data), 0) || soap_put___ns__CameraImageTake(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns__CameraImageTake(struct soap*, const struct __ns__CameraImageTake *, const char*, const char*);

#define soap_read___ns__CameraImageTake(soap, data) ( soap_begin_recv(soap) || !soap_get___ns__CameraImageTake(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns__CameraImageTake * SOAP_FMAC4 soap_get___ns__CameraImageTake(struct soap*, struct __ns__CameraImageTake *, const char*, const char*);

#define soap_new___ns__CameraImageTake(soap, n) soap_instantiate___ns__CameraImageTake(soap, n, NULL, NULL, NULL)


#define soap_delete___ns__CameraImageTake(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns__CameraImageTake * SOAP_FMAC2 soap_instantiate___ns__CameraImageTake(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns__CameraImageTake(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns__ScopePositionGet
#define SOAP_TYPE___ns__ScopePositionGet (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns__ScopePositionGet(struct soap*, struct __ns__ScopePositionGet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns__ScopePositionGet(struct soap*, const struct __ns__ScopePositionGet *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns__ScopePositionGet(struct soap*, const char*, int, const struct __ns__ScopePositionGet *, const char*);
SOAP_FMAC3 struct __ns__ScopePositionGet * SOAP_FMAC4 soap_in___ns__ScopePositionGet(struct soap*, const char*, struct __ns__ScopePositionGet *, const char*);

#define soap_write___ns__ScopePositionGet(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns__ScopePositionGet(soap, data), 0) || soap_put___ns__ScopePositionGet(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns__ScopePositionGet(struct soap*, const struct __ns__ScopePositionGet *, const char*, const char*);

#define soap_read___ns__ScopePositionGet(soap, data) ( soap_begin_recv(soap) || !soap_get___ns__ScopePositionGet(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns__ScopePositionGet * SOAP_FMAC4 soap_get___ns__ScopePositionGet(struct soap*, struct __ns__ScopePositionGet *, const char*, const char*);

#define soap_new___ns__ScopePositionGet(soap, n) soap_instantiate___ns__ScopePositionGet(soap, n, NULL, NULL, NULL)


#define soap_delete___ns__ScopePositionGet(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns__ScopePositionGet * SOAP_FMAC2 soap_instantiate___ns__ScopePositionGet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns__ScopePositionGet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns__ScopePositionSet
#define SOAP_TYPE___ns__ScopePositionSet (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns__ScopePositionSet(struct soap*, struct __ns__ScopePositionSet *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns__ScopePositionSet(struct soap*, const struct __ns__ScopePositionSet *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns__ScopePositionSet(struct soap*, const char*, int, const struct __ns__ScopePositionSet *, const char*);
SOAP_FMAC3 struct __ns__ScopePositionSet * SOAP_FMAC4 soap_in___ns__ScopePositionSet(struct soap*, const char*, struct __ns__ScopePositionSet *, const char*);

#define soap_write___ns__ScopePositionSet(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns__ScopePositionSet(soap, data), 0) || soap_put___ns__ScopePositionSet(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns__ScopePositionSet(struct soap*, const struct __ns__ScopePositionSet *, const char*, const char*);

#define soap_read___ns__ScopePositionSet(soap, data) ( soap_begin_recv(soap) || !soap_get___ns__ScopePositionSet(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns__ScopePositionSet * SOAP_FMAC4 soap_get___ns__ScopePositionSet(struct soap*, struct __ns__ScopePositionSet *, const char*, const char*);

#define soap_new___ns__ScopePositionSet(soap, n) soap_instantiate___ns__ScopePositionSet(soap, n, NULL, NULL, NULL)


#define soap_delete___ns__ScopePositionSet(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns__ScopePositionSet * SOAP_FMAC2 soap_instantiate___ns__ScopePositionSet(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns__ScopePositionSet(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE___ns__ImageSolve
#define SOAP_TYPE___ns__ImageSolve (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default___ns__ImageSolve(struct soap*, struct __ns__ImageSolve *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize___ns__ImageSolve(struct soap*, const struct __ns__ImageSolve *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out___ns__ImageSolve(struct soap*, const char*, int, const struct __ns__ImageSolve *, const char*);
SOAP_FMAC3 struct __ns__ImageSolve * SOAP_FMAC4 soap_in___ns__ImageSolve(struct soap*, const char*, struct __ns__ImageSolve *, const char*);

#define soap_write___ns__ImageSolve(soap, data) ( soap_begin_send(soap) || (soap_serialize___ns__ImageSolve(soap, data), 0) || soap_put___ns__ImageSolve(soap, data, NULL, NULL) || soap_end_send(soap) )


SOAP_FMAC3 int SOAP_FMAC4 soap_put___ns__ImageSolve(struct soap*, const struct __ns__ImageSolve *, const char*, const char*);

#define soap_read___ns__ImageSolve(soap, data) ( soap_begin_recv(soap) || !soap_get___ns__ImageSolve(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct __ns__ImageSolve * SOAP_FMAC4 soap_get___ns__ImageSolve(struct soap*, struct __ns__ImageSolve *, const char*, const char*);

#define soap_new___ns__ImageSolve(soap, n) soap_instantiate___ns__ImageSolve(soap, n, NULL, NULL, NULL)


#define soap_delete___ns__ImageSolve(soap, p) soap_delete(soap, p)

SOAP_FMAC1 struct __ns__ImageSolve * SOAP_FMAC2 soap_instantiate___ns__ImageSolve(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy___ns__ImageSolve(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Reason(soap, data), 0) || soap_put_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Detail(soap, data), 0) || soap_put_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerToSOAP_ENV__Code(soap, data), 0) || soap_put_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons__ScopeFocusAdjustResponseType
#define SOAP_TYPE_PointerTons__ScopeFocusAdjustResponseType (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__ScopeFocusAdjustResponseType(struct soap*, ns__ScopeFocusAdjustResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__ScopeFocusAdjustResponseType(struct soap*, const char *, int, ns__ScopeFocusAdjustResponseType *const*, const char *);
SOAP_FMAC3 ns__ScopeFocusAdjustResponseType ** SOAP_FMAC4 soap_in_PointerTons__ScopeFocusAdjustResponseType(struct soap*, const char*, ns__ScopeFocusAdjustResponseType **, const char*);

#define soap_write_PointerTons__ScopeFocusAdjustResponseType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__ScopeFocusAdjustResponseType(soap, data), 0) || soap_put_PointerTons__ScopeFocusAdjustResponseType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__ScopeFocusAdjustResponseType(struct soap*, ns__ScopeFocusAdjustResponseType *const*, const char*, const char*);

#define soap_read_PointerTons__ScopeFocusAdjustResponseType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__ScopeFocusAdjustResponseType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopeFocusAdjustResponseType ** SOAP_FMAC4 soap_get_PointerTons__ScopeFocusAdjustResponseType(struct soap*, ns__ScopeFocusAdjustResponseType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__ScopeFocusAdjustRequestType
#define SOAP_TYPE_PointerTons__ScopeFocusAdjustRequestType (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__ScopeFocusAdjustRequestType(struct soap*, ns__ScopeFocusAdjustRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__ScopeFocusAdjustRequestType(struct soap*, const char *, int, ns__ScopeFocusAdjustRequestType *const*, const char *);
SOAP_FMAC3 ns__ScopeFocusAdjustRequestType ** SOAP_FMAC4 soap_in_PointerTons__ScopeFocusAdjustRequestType(struct soap*, const char*, ns__ScopeFocusAdjustRequestType **, const char*);

#define soap_write_PointerTons__ScopeFocusAdjustRequestType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__ScopeFocusAdjustRequestType(soap, data), 0) || soap_put_PointerTons__ScopeFocusAdjustRequestType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__ScopeFocusAdjustRequestType(struct soap*, ns__ScopeFocusAdjustRequestType *const*, const char*, const char*);

#define soap_read_PointerTons__ScopeFocusAdjustRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__ScopeFocusAdjustRequestType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopeFocusAdjustRequestType ** SOAP_FMAC4 soap_get_PointerTons__ScopeFocusAdjustRequestType(struct soap*, ns__ScopeFocusAdjustRequestType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__CameraImageTakeResponseType
#define SOAP_TYPE_PointerTons__CameraImageTakeResponseType (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__CameraImageTakeResponseType(struct soap*, ns__CameraImageTakeResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__CameraImageTakeResponseType(struct soap*, const char *, int, ns__CameraImageTakeResponseType *const*, const char *);
SOAP_FMAC3 ns__CameraImageTakeResponseType ** SOAP_FMAC4 soap_in_PointerTons__CameraImageTakeResponseType(struct soap*, const char*, ns__CameraImageTakeResponseType **, const char*);

#define soap_write_PointerTons__CameraImageTakeResponseType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__CameraImageTakeResponseType(soap, data), 0) || soap_put_PointerTons__CameraImageTakeResponseType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__CameraImageTakeResponseType(struct soap*, ns__CameraImageTakeResponseType *const*, const char*, const char*);

#define soap_read_PointerTons__CameraImageTakeResponseType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__CameraImageTakeResponseType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__CameraImageTakeResponseType ** SOAP_FMAC4 soap_get_PointerTons__CameraImageTakeResponseType(struct soap*, ns__CameraImageTakeResponseType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__CameraImageTakeRequestType
#define SOAP_TYPE_PointerTons__CameraImageTakeRequestType (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__CameraImageTakeRequestType(struct soap*, ns__CameraImageTakeRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__CameraImageTakeRequestType(struct soap*, const char *, int, ns__CameraImageTakeRequestType *const*, const char *);
SOAP_FMAC3 ns__CameraImageTakeRequestType ** SOAP_FMAC4 soap_in_PointerTons__CameraImageTakeRequestType(struct soap*, const char*, ns__CameraImageTakeRequestType **, const char*);

#define soap_write_PointerTons__CameraImageTakeRequestType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__CameraImageTakeRequestType(soap, data), 0) || soap_put_PointerTons__CameraImageTakeRequestType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__CameraImageTakeRequestType(struct soap*, ns__CameraImageTakeRequestType *const*, const char*, const char*);

#define soap_read_PointerTons__CameraImageTakeRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__CameraImageTakeRequestType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__CameraImageTakeRequestType ** SOAP_FMAC4 soap_get_PointerTons__CameraImageTakeRequestType(struct soap*, ns__CameraImageTakeRequestType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__ScopePositionGetResponseType
#define SOAP_TYPE_PointerTons__ScopePositionGetResponseType (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__ScopePositionGetResponseType(struct soap*, ns__ScopePositionGetResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__ScopePositionGetResponseType(struct soap*, const char *, int, ns__ScopePositionGetResponseType *const*, const char *);
SOAP_FMAC3 ns__ScopePositionGetResponseType ** SOAP_FMAC4 soap_in_PointerTons__ScopePositionGetResponseType(struct soap*, const char*, ns__ScopePositionGetResponseType **, const char*);

#define soap_write_PointerTons__ScopePositionGetResponseType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__ScopePositionGetResponseType(soap, data), 0) || soap_put_PointerTons__ScopePositionGetResponseType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__ScopePositionGetResponseType(struct soap*, ns__ScopePositionGetResponseType *const*, const char*, const char*);

#define soap_read_PointerTons__ScopePositionGetResponseType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__ScopePositionGetResponseType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopePositionGetResponseType ** SOAP_FMAC4 soap_get_PointerTons__ScopePositionGetResponseType(struct soap*, ns__ScopePositionGetResponseType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__ScopePositionGetRequestType
#define SOAP_TYPE_PointerTons__ScopePositionGetRequestType (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__ScopePositionGetRequestType(struct soap*, ns__ScopePositionGetRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__ScopePositionGetRequestType(struct soap*, const char *, int, ns__ScopePositionGetRequestType *const*, const char *);
SOAP_FMAC3 ns__ScopePositionGetRequestType ** SOAP_FMAC4 soap_in_PointerTons__ScopePositionGetRequestType(struct soap*, const char*, ns__ScopePositionGetRequestType **, const char*);

#define soap_write_PointerTons__ScopePositionGetRequestType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__ScopePositionGetRequestType(soap, data), 0) || soap_put_PointerTons__ScopePositionGetRequestType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__ScopePositionGetRequestType(struct soap*, ns__ScopePositionGetRequestType *const*, const char*, const char*);

#define soap_read_PointerTons__ScopePositionGetRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__ScopePositionGetRequestType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopePositionGetRequestType ** SOAP_FMAC4 soap_get_PointerTons__ScopePositionGetRequestType(struct soap*, ns__ScopePositionGetRequestType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__ScopePositionSetResponseType
#define SOAP_TYPE_PointerTons__ScopePositionSetResponseType (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__ScopePositionSetResponseType(struct soap*, ns__ScopePositionSetResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__ScopePositionSetResponseType(struct soap*, const char *, int, ns__ScopePositionSetResponseType *const*, const char *);
SOAP_FMAC3 ns__ScopePositionSetResponseType ** SOAP_FMAC4 soap_in_PointerTons__ScopePositionSetResponseType(struct soap*, const char*, ns__ScopePositionSetResponseType **, const char*);

#define soap_write_PointerTons__ScopePositionSetResponseType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__ScopePositionSetResponseType(soap, data), 0) || soap_put_PointerTons__ScopePositionSetResponseType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__ScopePositionSetResponseType(struct soap*, ns__ScopePositionSetResponseType *const*, const char*, const char*);

#define soap_read_PointerTons__ScopePositionSetResponseType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__ScopePositionSetResponseType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopePositionSetResponseType ** SOAP_FMAC4 soap_get_PointerTons__ScopePositionSetResponseType(struct soap*, ns__ScopePositionSetResponseType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__ScopePositionSetRequestType
#define SOAP_TYPE_PointerTons__ScopePositionSetRequestType (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__ScopePositionSetRequestType(struct soap*, ns__ScopePositionSetRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__ScopePositionSetRequestType(struct soap*, const char *, int, ns__ScopePositionSetRequestType *const*, const char *);
SOAP_FMAC3 ns__ScopePositionSetRequestType ** SOAP_FMAC4 soap_in_PointerTons__ScopePositionSetRequestType(struct soap*, const char*, ns__ScopePositionSetRequestType **, const char*);

#define soap_write_PointerTons__ScopePositionSetRequestType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__ScopePositionSetRequestType(soap, data), 0) || soap_put_PointerTons__ScopePositionSetRequestType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__ScopePositionSetRequestType(struct soap*, ns__ScopePositionSetRequestType *const*, const char*, const char*);

#define soap_read_PointerTons__ScopePositionSetRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__ScopePositionSetRequestType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ScopePositionSetRequestType ** SOAP_FMAC4 soap_get_PointerTons__ScopePositionSetRequestType(struct soap*, ns__ScopePositionSetRequestType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__ImageSolveResponseType
#define SOAP_TYPE_PointerTons__ImageSolveResponseType (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__ImageSolveResponseType(struct soap*, ns__ImageSolveResponseType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__ImageSolveResponseType(struct soap*, const char *, int, ns__ImageSolveResponseType *const*, const char *);
SOAP_FMAC3 ns__ImageSolveResponseType ** SOAP_FMAC4 soap_in_PointerTons__ImageSolveResponseType(struct soap*, const char*, ns__ImageSolveResponseType **, const char*);

#define soap_write_PointerTons__ImageSolveResponseType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__ImageSolveResponseType(soap, data), 0) || soap_put_PointerTons__ImageSolveResponseType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__ImageSolveResponseType(struct soap*, ns__ImageSolveResponseType *const*, const char*, const char*);

#define soap_read_PointerTons__ImageSolveResponseType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__ImageSolveResponseType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ImageSolveResponseType ** SOAP_FMAC4 soap_get_PointerTons__ImageSolveResponseType(struct soap*, ns__ImageSolveResponseType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__ImageSolveRequestType
#define SOAP_TYPE_PointerTons__ImageSolveRequestType (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__ImageSolveRequestType(struct soap*, ns__ImageSolveRequestType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__ImageSolveRequestType(struct soap*, const char *, int, ns__ImageSolveRequestType *const*, const char *);
SOAP_FMAC3 ns__ImageSolveRequestType ** SOAP_FMAC4 soap_in_PointerTons__ImageSolveRequestType(struct soap*, const char*, ns__ImageSolveRequestType **, const char*);

#define soap_write_PointerTons__ImageSolveRequestType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__ImageSolveRequestType(soap, data), 0) || soap_put_PointerTons__ImageSolveRequestType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__ImageSolveRequestType(struct soap*, ns__ImageSolveRequestType *const*, const char*, const char*);

#define soap_read_PointerTons__ImageSolveRequestType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__ImageSolveRequestType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ImageSolveRequestType ** SOAP_FMAC4 soap_get_PointerTons__ImageSolveRequestType(struct soap*, ns__ImageSolveRequestType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__ImgObjDetectedType
#define SOAP_TYPE_PointerTons__ImgObjDetectedType (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__ImgObjDetectedType(struct soap*, ns__ImgObjDetectedType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__ImgObjDetectedType(struct soap*, const char *, int, ns__ImgObjDetectedType *const*, const char *);
SOAP_FMAC3 ns__ImgObjDetectedType ** SOAP_FMAC4 soap_in_PointerTons__ImgObjDetectedType(struct soap*, const char*, ns__ImgObjDetectedType **, const char*);

#define soap_write_PointerTons__ImgObjDetectedType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__ImgObjDetectedType(soap, data), 0) || soap_put_PointerTons__ImgObjDetectedType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__ImgObjDetectedType(struct soap*, ns__ImgObjDetectedType *const*, const char*, const char*);

#define soap_read_PointerTons__ImgObjDetectedType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__ImgObjDetectedType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ImgObjDetectedType ** SOAP_FMAC4 soap_get_PointerTons__ImgObjDetectedType(struct soap*, ns__ImgObjDetectedType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__ImgDataHeaderType
#define SOAP_TYPE_PointerTons__ImgDataHeaderType (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__ImgDataHeaderType(struct soap*, ns__ImgDataHeaderType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__ImgDataHeaderType(struct soap*, const char *, int, ns__ImgDataHeaderType *const*, const char *);
SOAP_FMAC3 ns__ImgDataHeaderType ** SOAP_FMAC4 soap_in_PointerTons__ImgDataHeaderType(struct soap*, const char*, ns__ImgDataHeaderType **, const char*);

#define soap_write_PointerTons__ImgDataHeaderType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__ImgDataHeaderType(soap, data), 0) || soap_put_PointerTons__ImgDataHeaderType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__ImgDataHeaderType(struct soap*, ns__ImgDataHeaderType *const*, const char*, const char*);

#define soap_read_PointerTons__ImgDataHeaderType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__ImgDataHeaderType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ImgDataHeaderType ** SOAP_FMAC4 soap_get_PointerTons__ImgDataHeaderType(struct soap*, ns__ImgDataHeaderType **, const char*, const char*);

#ifndef SOAP_TYPE_PointerTons__ResponseStatusType
#define SOAP_TYPE_PointerTons__ResponseStatusType (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons__ResponseStatusType(struct soap*, ns__ResponseStatusType *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons__ResponseStatusType(struct soap*, const char *, int, ns__ResponseStatusType *const*, const char *);
SOAP_FMAC3 ns__ResponseStatusType ** SOAP_FMAC4 soap_in_PointerTons__ResponseStatusType(struct soap*, const char*, ns__ResponseStatusType **, const char*);

#define soap_write_PointerTons__ResponseStatusType(soap, data) ( soap_begin_send(soap) || (soap_serialize_PointerTons__ResponseStatusType(soap, data), 0) || soap_put_PointerTons__ResponseStatusType(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons__ResponseStatusType(struct soap*, ns__ResponseStatusType *const*, const char*, const char*);

#define soap_read_PointerTons__ResponseStatusType(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerTons__ResponseStatusType(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 ns__ResponseStatusType ** SOAP_FMAC4 soap_get_PointerTons__ResponseStatusType(struct soap*, ns__ResponseStatusType **, const char*, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#define soap_write__QName(soap, data) ( soap_begin_send(soap) || (soap_serialize__QName(soap, data), 0) || soap_put__QName(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#define soap_write_string(soap, data) ( soap_begin_send(soap) || (soap_serialize_string(soap, data), 0) || soap_put_string(soap, data, NULL, NULL) || soap_end_send(soap) )

SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap) )

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef SOAP_TYPE_std__vectorTemplateOfPointerTons__ImgObjDetectedType
#define SOAP_TYPE_std__vectorTemplateOfPointerTons__ImgObjDetectedType (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfPointerTons__ImgObjDetectedType(struct soap*, std::vector<ns__ImgObjDetectedType * >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfPointerTons__ImgObjDetectedType(struct soap*, const std::vector<ns__ImgObjDetectedType * >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfPointerTons__ImgObjDetectedType(struct soap*, const char*, int, const std::vector<ns__ImgObjDetectedType * >*, const char*);
SOAP_FMAC3 std::vector<ns__ImgObjDetectedType * >* SOAP_FMAC4 soap_in_std__vectorTemplateOfPointerTons__ImgObjDetectedType(struct soap*, const char*, std::vector<ns__ImgObjDetectedType * >*, const char*);

#define soap_new_std__vectorTemplateOfPointerTons__ImgObjDetectedType(soap, n) soap_instantiate_std__vectorTemplateOfPointerTons__ImgObjDetectedType(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfPointerTons__ImgObjDetectedType(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<ns__ImgObjDetectedType * > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfPointerTons__ImgObjDetectedType(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfPointerTons__ImgObjDetectedType(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_std__vectorTemplateOfstd__string
#define SOAP_TYPE_std__vectorTemplateOfstd__string (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__vectorTemplateOfstd__string(struct soap*, std::vector<std::string >*);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__vectorTemplateOfstd__string(struct soap*, const std::vector<std::string >*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__vectorTemplateOfstd__string(struct soap*, const char*, int, const std::vector<std::string >*, const char*);
SOAP_FMAC3 std::vector<std::string >* SOAP_FMAC4 soap_in_std__vectorTemplateOfstd__string(struct soap*, const char*, std::vector<std::string >*, const char*);

#define soap_new_std__vectorTemplateOfstd__string(soap, n) soap_instantiate_std__vectorTemplateOfstd__string(soap, n, NULL, NULL, NULL)


#define soap_delete_std__vectorTemplateOfstd__string(soap, p) soap_delete(soap, p)

SOAP_FMAC1 std::vector<std::string > * SOAP_FMAC2 soap_instantiate_std__vectorTemplateOfstd__string(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__vectorTemplateOfstd__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

/* End of soapH.h */
