/* soapUnimapSoapXmlBindingService.h
   Generated by gSOAP 2.7.16 from unimap_service.h
   Copyright(C) 2000-2010, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapUnimapSoapXmlBindingService_H
#define soapUnimapSoapXmlBindingService_H
#include "soapH.h"
class SOAP_CMAC UnimapSoapXmlBindingService : public soap
{ public:
	/// Constructor
	UnimapSoapXmlBindingService();
	/// Constructor with copy of another engine state
	UnimapSoapXmlBindingService(const struct soap&);
	/// Constructor with engine input+output mode control
	UnimapSoapXmlBindingService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	UnimapSoapXmlBindingService(soap_mode imode, soap_mode omode);
	/// Destructor, also frees all deserialized data
	virtual ~UnimapSoapXmlBindingService();
	/// Delete all deserialized data (uses soap_destroy and soap_end)
	virtual	void destroy();
	/// Initializer used by constructor
	virtual	void UnimapSoapXmlBindingService_init(soap_mode imode, soap_mode omode);
	/// Create a copy
	virtual	UnimapSoapXmlBindingService *copy();
	/// Force close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
	virtual	void soap_stream_fault(std::ostream&);
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Run simple single-thread iterative service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error code or SOAP_OK)
	virtual	int dispatch();

	///
	/// Service operations (you should define these):
	///

	/// Web service operation 'ImageSolve' (returns error code or SOAP_OK)
	virtual	int ImageSolve(ns__ImageSolveRequestType *ns__ImageSolveRequest, ns__ImageSolveResponseType *ns__ImageSolveResponse);

	/// Web service operation 'ScopePositionSet' (returns error code or SOAP_OK)
	virtual	int ScopePositionSet(ns__ScopePositionSetRequestType *input, ns__ScopePositionSetResponseType *result);

	/// Web service operation 'ScopePositionGet' (returns error code or SOAP_OK)
	virtual	int ScopePositionGet(ns__ScopePositionGetRequestType *input, ns__ScopePositionGetResponseType *result);

	/// Web service operation 'CameraImageTake' (returns error code or SOAP_OK)
	virtual	int CameraImageTake(ns__CameraImageTakeRequestType *input, ns__CameraImageTakeResponseType *result);

	/// Web service operation 'ScopeFocusAdjust' (returns error code or SOAP_OK)
	virtual	int ScopeFocusAdjust(ns__ScopeFocusAdjustRequestType *input, ns__ScopeFocusAdjustResponseType *result);
};
#endif
