/* soapH.h
   Generated by gSOAP 2.7.10 from interop_all.h
   Copyright(C) 2000-2008, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_xsd__int
#define SOAP_TYPE_xsd__int (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__int(struct soap*, long *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__int(struct soap*, const long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__int(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_xsd__int(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_xsd__int(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_long
#define SOAP_TYPE_long (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_long(struct soap*, long *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_long(struct soap*, const long *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_long(struct soap*, const char*, int, const long *, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_get_long(struct soap*, long *, const char*, const char*);
SOAP_FMAC3 long * SOAP_FMAC4 soap_in_long(struct soap*, const char*, long *, const char*);

#ifndef SOAP_TYPE_xsd__float
#define SOAP_TYPE_xsd__float (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_xsd__float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_xsd__float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_unsignedByte
#define SOAP_TYPE_unsignedByte (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedByte(struct soap*, unsigned char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedByte(struct soap*, const unsigned char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedByte(struct soap*, const char*, int, const unsigned char *, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_get_unsignedByte(struct soap*, unsigned char *, const char*, const char*);
SOAP_FMAC3 unsigned char * SOAP_FMAC4 soap_in_unsignedByte(struct soap*, const char*, unsigned char *, const char*);

#ifndef SOAP_TYPE_unsignedInt
#define SOAP_TYPE_unsignedInt (61)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_unsignedInt(struct soap*, unsigned int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_unsignedInt(struct soap*, const unsigned int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_unsignedInt(struct soap*, const char*, int, const unsigned int *, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_get_unsignedInt(struct soap*, unsigned int *, const char*, const char*);
SOAP_FMAC3 unsigned int * SOAP_FMAC4 soap_in_unsignedInt(struct soap*, const char*, unsigned int *, const char*);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, bool *);

#ifndef SOAP_TYPE_bool
#define SOAP_TYPE_bool (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_bool(struct soap*, bool *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_bool(struct soap*, const bool *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_bool(struct soap*, const char*, int, const bool *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_bool2s(struct soap*, bool);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_get_bool(struct soap*, bool *, const char*, const char*);
SOAP_FMAC3 bool * SOAP_FMAC4 soap_in_bool(struct soap*, const char*, bool *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2bool(struct soap*, const char*, bool *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (124)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Fault * SOAP_FMAC6 soap_new_SOAP_ENV__Fault(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (123)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Reason * SOAP_FMAC6 soap_new_SOAP_ENV__Reason(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (120)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Detail * SOAP_FMAC6 soap_new_SOAP_ENV__Detail(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (118)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Code * SOAP_FMAC6 soap_new_SOAP_ENV__Code(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_m__echoVoid
#define SOAP_TYPE_m__echoVoid (117)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_m__echoVoid(struct soap*, struct m__echoVoid *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_m__echoVoid(struct soap*, const struct m__echoVoid *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_m__echoVoid(struct soap*, const struct m__echoVoid *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_m__echoVoid(struct soap*, const char*, int, const struct m__echoVoid *, const char*);
SOAP_FMAC3 struct m__echoVoid * SOAP_FMAC4 soap_get_m__echoVoid(struct soap*, struct m__echoVoid *, const char*, const char*);
SOAP_FMAC3 struct m__echoVoid * SOAP_FMAC4 soap_in_m__echoVoid(struct soap*, const char*, struct m__echoVoid *, const char*);
SOAP_FMAC5 struct m__echoVoid * SOAP_FMAC6 soap_new_m__echoVoid(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_m__echoVoid(struct soap*, struct m__echoVoid*);
SOAP_FMAC3 struct m__echoVoid * SOAP_FMAC4 soap_instantiate_m__echoVoid(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_m__echoVoid(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_m__echoVoidResponse
#define SOAP_TYPE_m__echoVoidResponse (114)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_m__echoVoidResponse(struct soap*, struct m__echoVoidResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_m__echoVoidResponse(struct soap*, const struct m__echoVoidResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_m__echoVoidResponse(struct soap*, const struct m__echoVoidResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_m__echoVoidResponse(struct soap*, const char*, int, const struct m__echoVoidResponse *, const char*);
SOAP_FMAC3 struct m__echoVoidResponse * SOAP_FMAC4 soap_get_m__echoVoidResponse(struct soap*, struct m__echoVoidResponse *, const char*, const char*);
SOAP_FMAC3 struct m__echoVoidResponse * SOAP_FMAC4 soap_in_m__echoVoidResponse(struct soap*, const char*, struct m__echoVoidResponse *, const char*);
SOAP_FMAC5 struct m__echoVoidResponse * SOAP_FMAC6 soap_new_m__echoVoidResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_m__echoVoidResponse(struct soap*, struct m__echoVoidResponse*);
SOAP_FMAC3 struct m__echoVoidResponse * SOAP_FMAC4 soap_instantiate_m__echoVoidResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_m__echoVoidResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (113)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);
SOAP_FMAC5 struct SOAP_ENV__Header * SOAP_FMAC6 soap_new_SOAP_ENV__Header(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns__echoNestedArray
#define SOAP_TYPE_ns__echoNestedArray (112)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoNestedArray(struct soap*, struct ns__echoNestedArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoNestedArray(struct soap*, const struct ns__echoNestedArray *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoNestedArray(struct soap*, const struct ns__echoNestedArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoNestedArray(struct soap*, const char*, int, const struct ns__echoNestedArray *, const char*);
SOAP_FMAC3 struct ns__echoNestedArray * SOAP_FMAC4 soap_get_ns__echoNestedArray(struct soap*, struct ns__echoNestedArray *, const char*, const char*);
SOAP_FMAC3 struct ns__echoNestedArray * SOAP_FMAC4 soap_in_ns__echoNestedArray(struct soap*, const char*, struct ns__echoNestedArray *, const char*);
SOAP_FMAC5 struct ns__echoNestedArray * SOAP_FMAC6 soap_new_ns__echoNestedArray(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoNestedArray(struct soap*, struct ns__echoNestedArray*);
SOAP_FMAC3 struct ns__echoNestedArray * SOAP_FMAC4 soap_instantiate_ns__echoNestedArray(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoNestedArray(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoNestedArrayResponse
#define SOAP_TYPE_ns__echoNestedArrayResponse (109)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoNestedArrayResponse(struct soap*, struct ns__echoNestedArrayResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoNestedArrayResponse(struct soap*, const struct ns__echoNestedArrayResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoNestedArrayResponse(struct soap*, const struct ns__echoNestedArrayResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoNestedArrayResponse(struct soap*, const char*, int, const struct ns__echoNestedArrayResponse *, const char*);
SOAP_FMAC3 struct ns__echoNestedArrayResponse * SOAP_FMAC4 soap_get_ns__echoNestedArrayResponse(struct soap*, struct ns__echoNestedArrayResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoNestedArrayResponse * SOAP_FMAC4 soap_in_ns__echoNestedArrayResponse(struct soap*, const char*, struct ns__echoNestedArrayResponse *, const char*);
SOAP_FMAC5 struct ns__echoNestedArrayResponse * SOAP_FMAC6 soap_new_ns__echoNestedArrayResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoNestedArrayResponse(struct soap*, struct ns__echoNestedArrayResponse*);
SOAP_FMAC3 struct ns__echoNestedArrayResponse * SOAP_FMAC4 soap_instantiate_ns__echoNestedArrayResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoNestedArrayResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_s__SOAPArrayStruct
#define SOAP_TYPE_s__SOAPArrayStruct (108)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_s__SOAPArrayStruct(struct soap*, struct s__SOAPArrayStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_s__SOAPArrayStruct(struct soap*, const struct s__SOAPArrayStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_s__SOAPArrayStruct(struct soap*, const struct s__SOAPArrayStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_s__SOAPArrayStruct(struct soap*, const char*, int, const struct s__SOAPArrayStruct *, const char*);
SOAP_FMAC3 struct s__SOAPArrayStruct * SOAP_FMAC4 soap_get_s__SOAPArrayStruct(struct soap*, struct s__SOAPArrayStruct *, const char*, const char*);
SOAP_FMAC3 struct s__SOAPArrayStruct * SOAP_FMAC4 soap_in_s__SOAPArrayStruct(struct soap*, const char*, struct s__SOAPArrayStruct *, const char*);
SOAP_FMAC5 struct s__SOAPArrayStruct * SOAP_FMAC6 soap_new_s__SOAPArrayStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_s__SOAPArrayStruct(struct soap*, struct s__SOAPArrayStruct*);
SOAP_FMAC3 struct s__SOAPArrayStruct * SOAP_FMAC4 soap_instantiate_s__SOAPArrayStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_s__SOAPArrayStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoNestedStruct
#define SOAP_TYPE_ns__echoNestedStruct (107)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoNestedStruct(struct soap*, struct ns__echoNestedStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoNestedStruct(struct soap*, const struct ns__echoNestedStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoNestedStruct(struct soap*, const struct ns__echoNestedStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoNestedStruct(struct soap*, const char*, int, const struct ns__echoNestedStruct *, const char*);
SOAP_FMAC3 struct ns__echoNestedStruct * SOAP_FMAC4 soap_get_ns__echoNestedStruct(struct soap*, struct ns__echoNestedStruct *, const char*, const char*);
SOAP_FMAC3 struct ns__echoNestedStruct * SOAP_FMAC4 soap_in_ns__echoNestedStruct(struct soap*, const char*, struct ns__echoNestedStruct *, const char*);
SOAP_FMAC5 struct ns__echoNestedStruct * SOAP_FMAC6 soap_new_ns__echoNestedStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoNestedStruct(struct soap*, struct ns__echoNestedStruct*);
SOAP_FMAC3 struct ns__echoNestedStruct * SOAP_FMAC4 soap_instantiate_ns__echoNestedStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoNestedStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoNestedStructResponse
#define SOAP_TYPE_ns__echoNestedStructResponse (104)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoNestedStructResponse(struct soap*, struct ns__echoNestedStructResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoNestedStructResponse(struct soap*, const struct ns__echoNestedStructResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoNestedStructResponse(struct soap*, const struct ns__echoNestedStructResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoNestedStructResponse(struct soap*, const char*, int, const struct ns__echoNestedStructResponse *, const char*);
SOAP_FMAC3 struct ns__echoNestedStructResponse * SOAP_FMAC4 soap_get_ns__echoNestedStructResponse(struct soap*, struct ns__echoNestedStructResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoNestedStructResponse * SOAP_FMAC4 soap_in_ns__echoNestedStructResponse(struct soap*, const char*, struct ns__echoNestedStructResponse *, const char*);
SOAP_FMAC5 struct ns__echoNestedStructResponse * SOAP_FMAC6 soap_new_ns__echoNestedStructResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoNestedStructResponse(struct soap*, struct ns__echoNestedStructResponse*);
SOAP_FMAC3 struct ns__echoNestedStructResponse * SOAP_FMAC4 soap_instantiate_ns__echoNestedStructResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoNestedStructResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_s__SOAPStructStruct
#define SOAP_TYPE_s__SOAPStructStruct (103)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_s__SOAPStructStruct(struct soap*, struct s__SOAPStructStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_s__SOAPStructStruct(struct soap*, const struct s__SOAPStructStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_s__SOAPStructStruct(struct soap*, const struct s__SOAPStructStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_s__SOAPStructStruct(struct soap*, const char*, int, const struct s__SOAPStructStruct *, const char*);
SOAP_FMAC3 struct s__SOAPStructStruct * SOAP_FMAC4 soap_get_s__SOAPStructStruct(struct soap*, struct s__SOAPStructStruct *, const char*, const char*);
SOAP_FMAC3 struct s__SOAPStructStruct * SOAP_FMAC4 soap_in_s__SOAPStructStruct(struct soap*, const char*, struct s__SOAPStructStruct *, const char*);
SOAP_FMAC5 struct s__SOAPStructStruct * SOAP_FMAC6 soap_new_s__SOAPStructStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_s__SOAPStructStruct(struct soap*, struct s__SOAPStructStruct*);
SOAP_FMAC3 struct s__SOAPStructStruct * SOAP_FMAC4 soap_instantiate_s__SOAPStructStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_s__SOAPStructStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echo2DStringArray
#define SOAP_TYPE_ns__echo2DStringArray (102)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echo2DStringArray(struct soap*, struct ns__echo2DStringArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echo2DStringArray(struct soap*, const struct ns__echo2DStringArray *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echo2DStringArray(struct soap*, const struct ns__echo2DStringArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echo2DStringArray(struct soap*, const char*, int, const struct ns__echo2DStringArray *, const char*);
SOAP_FMAC3 struct ns__echo2DStringArray * SOAP_FMAC4 soap_get_ns__echo2DStringArray(struct soap*, struct ns__echo2DStringArray *, const char*, const char*);
SOAP_FMAC3 struct ns__echo2DStringArray * SOAP_FMAC4 soap_in_ns__echo2DStringArray(struct soap*, const char*, struct ns__echo2DStringArray *, const char*);
SOAP_FMAC5 struct ns__echo2DStringArray * SOAP_FMAC6 soap_new_ns__echo2DStringArray(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echo2DStringArray(struct soap*, struct ns__echo2DStringArray*);
SOAP_FMAC3 struct ns__echo2DStringArray * SOAP_FMAC4 soap_instantiate_ns__echo2DStringArray(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echo2DStringArray(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echo2DStringArrayResponse
#define SOAP_TYPE_ns__echo2DStringArrayResponse (101)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echo2DStringArrayResponse(struct soap*, struct ns__echo2DStringArrayResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echo2DStringArrayResponse(struct soap*, const struct ns__echo2DStringArrayResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echo2DStringArrayResponse(struct soap*, const struct ns__echo2DStringArrayResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echo2DStringArrayResponse(struct soap*, const char*, int, const struct ns__echo2DStringArrayResponse *, const char*);
SOAP_FMAC3 struct ns__echo2DStringArrayResponse * SOAP_FMAC4 soap_get_ns__echo2DStringArrayResponse(struct soap*, struct ns__echo2DStringArrayResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echo2DStringArrayResponse * SOAP_FMAC4 soap_in_ns__echo2DStringArrayResponse(struct soap*, const char*, struct ns__echo2DStringArrayResponse *, const char*);
SOAP_FMAC5 struct ns__echo2DStringArrayResponse * SOAP_FMAC6 soap_new_ns__echo2DStringArrayResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echo2DStringArrayResponse(struct soap*, struct ns__echo2DStringArrayResponse*);
SOAP_FMAC3 struct ns__echo2DStringArrayResponse * SOAP_FMAC4 soap_instantiate_ns__echo2DStringArrayResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echo2DStringArrayResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOfstring2D
#define SOAP_TYPE_ArrayOfstring2D (97)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfstring2D(struct soap*, struct ArrayOfstring2D *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfstring2D(struct soap*, struct ArrayOfstring2D const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfstring2D(struct soap*, const struct ArrayOfstring2D *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfstring2D(struct soap*, const char*, int, const struct ArrayOfstring2D *, const char*);
SOAP_FMAC3 struct ArrayOfstring2D * SOAP_FMAC4 soap_get_ArrayOfstring2D(struct soap*, struct ArrayOfstring2D *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfstring2D * SOAP_FMAC4 soap_in_ArrayOfstring2D(struct soap*, const char*, struct ArrayOfstring2D *, const char*);
SOAP_FMAC5 struct ArrayOfstring2D * SOAP_FMAC6 soap_new_ArrayOfstring2D(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOfstring2D(struct soap*, struct ArrayOfstring2D*);
SOAP_FMAC3 struct ArrayOfstring2D * SOAP_FMAC4 soap_instantiate_ArrayOfstring2D(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOfstring2D(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoSimpleTypesAsStruct
#define SOAP_TYPE_ns__echoSimpleTypesAsStruct (96)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoSimpleTypesAsStruct(struct soap*, struct ns__echoSimpleTypesAsStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoSimpleTypesAsStruct(struct soap*, const struct ns__echoSimpleTypesAsStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoSimpleTypesAsStruct(struct soap*, const struct ns__echoSimpleTypesAsStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoSimpleTypesAsStruct(struct soap*, const char*, int, const struct ns__echoSimpleTypesAsStruct *, const char*);
SOAP_FMAC3 struct ns__echoSimpleTypesAsStruct * SOAP_FMAC4 soap_get_ns__echoSimpleTypesAsStruct(struct soap*, struct ns__echoSimpleTypesAsStruct *, const char*, const char*);
SOAP_FMAC3 struct ns__echoSimpleTypesAsStruct * SOAP_FMAC4 soap_in_ns__echoSimpleTypesAsStruct(struct soap*, const char*, struct ns__echoSimpleTypesAsStruct *, const char*);
SOAP_FMAC5 struct ns__echoSimpleTypesAsStruct * SOAP_FMAC6 soap_new_ns__echoSimpleTypesAsStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoSimpleTypesAsStruct(struct soap*, struct ns__echoSimpleTypesAsStruct*);
SOAP_FMAC3 struct ns__echoSimpleTypesAsStruct * SOAP_FMAC4 soap_instantiate_ns__echoSimpleTypesAsStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoSimpleTypesAsStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoSimpleTypesAsStructResponse
#define SOAP_TYPE_ns__echoSimpleTypesAsStructResponse (93)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoSimpleTypesAsStructResponse(struct soap*, struct ns__echoSimpleTypesAsStructResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoSimpleTypesAsStructResponse(struct soap*, const struct ns__echoSimpleTypesAsStructResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoSimpleTypesAsStructResponse(struct soap*, const struct ns__echoSimpleTypesAsStructResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoSimpleTypesAsStructResponse(struct soap*, const char*, int, const struct ns__echoSimpleTypesAsStructResponse *, const char*);
SOAP_FMAC3 struct ns__echoSimpleTypesAsStructResponse * SOAP_FMAC4 soap_get_ns__echoSimpleTypesAsStructResponse(struct soap*, struct ns__echoSimpleTypesAsStructResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoSimpleTypesAsStructResponse * SOAP_FMAC4 soap_in_ns__echoSimpleTypesAsStructResponse(struct soap*, const char*, struct ns__echoSimpleTypesAsStructResponse *, const char*);
SOAP_FMAC5 struct ns__echoSimpleTypesAsStructResponse * SOAP_FMAC6 soap_new_ns__echoSimpleTypesAsStructResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoSimpleTypesAsStructResponse(struct soap*, struct ns__echoSimpleTypesAsStructResponse*);
SOAP_FMAC3 struct ns__echoSimpleTypesAsStructResponse * SOAP_FMAC4 soap_instantiate_ns__echoSimpleTypesAsStructResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoSimpleTypesAsStructResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoStructAsSimpleTypes
#define SOAP_TYPE_ns__echoStructAsSimpleTypes (92)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoStructAsSimpleTypes(struct soap*, struct ns__echoStructAsSimpleTypes *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoStructAsSimpleTypes(struct soap*, const struct ns__echoStructAsSimpleTypes *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoStructAsSimpleTypes(struct soap*, const struct ns__echoStructAsSimpleTypes *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoStructAsSimpleTypes(struct soap*, const char*, int, const struct ns__echoStructAsSimpleTypes *, const char*);
SOAP_FMAC3 struct ns__echoStructAsSimpleTypes * SOAP_FMAC4 soap_get_ns__echoStructAsSimpleTypes(struct soap*, struct ns__echoStructAsSimpleTypes *, const char*, const char*);
SOAP_FMAC3 struct ns__echoStructAsSimpleTypes * SOAP_FMAC4 soap_in_ns__echoStructAsSimpleTypes(struct soap*, const char*, struct ns__echoStructAsSimpleTypes *, const char*);
SOAP_FMAC5 struct ns__echoStructAsSimpleTypes * SOAP_FMAC6 soap_new_ns__echoStructAsSimpleTypes(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoStructAsSimpleTypes(struct soap*, struct ns__echoStructAsSimpleTypes*);
SOAP_FMAC3 struct ns__echoStructAsSimpleTypes * SOAP_FMAC4 soap_instantiate_ns__echoStructAsSimpleTypes(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoStructAsSimpleTypes(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoStructAsSimpleTypesResponse
#define SOAP_TYPE_ns__echoStructAsSimpleTypesResponse (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoStructAsSimpleTypesResponse(struct soap*, struct ns__echoStructAsSimpleTypesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoStructAsSimpleTypesResponse(struct soap*, const struct ns__echoStructAsSimpleTypesResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoStructAsSimpleTypesResponse(struct soap*, const struct ns__echoStructAsSimpleTypesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoStructAsSimpleTypesResponse(struct soap*, const char*, int, const struct ns__echoStructAsSimpleTypesResponse *, const char*);
SOAP_FMAC3 struct ns__echoStructAsSimpleTypesResponse * SOAP_FMAC4 soap_get_ns__echoStructAsSimpleTypesResponse(struct soap*, struct ns__echoStructAsSimpleTypesResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoStructAsSimpleTypesResponse * SOAP_FMAC4 soap_in_ns__echoStructAsSimpleTypesResponse(struct soap*, const char*, struct ns__echoStructAsSimpleTypesResponse *, const char*);
SOAP_FMAC5 struct ns__echoStructAsSimpleTypesResponse * SOAP_FMAC6 soap_new_ns__echoStructAsSimpleTypesResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoStructAsSimpleTypesResponse(struct soap*, struct ns__echoStructAsSimpleTypesResponse*);
SOAP_FMAC3 struct ns__echoStructAsSimpleTypesResponse * SOAP_FMAC4 soap_instantiate_ns__echoStructAsSimpleTypesResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoStructAsSimpleTypesResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoBoolean
#define SOAP_TYPE_ns__echoBoolean (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoBoolean(struct soap*, struct ns__echoBoolean *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoBoolean(struct soap*, const struct ns__echoBoolean *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoBoolean(struct soap*, const struct ns__echoBoolean *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoBoolean(struct soap*, const char*, int, const struct ns__echoBoolean *, const char*);
SOAP_FMAC3 struct ns__echoBoolean * SOAP_FMAC4 soap_get_ns__echoBoolean(struct soap*, struct ns__echoBoolean *, const char*, const char*);
SOAP_FMAC3 struct ns__echoBoolean * SOAP_FMAC4 soap_in_ns__echoBoolean(struct soap*, const char*, struct ns__echoBoolean *, const char*);
SOAP_FMAC5 struct ns__echoBoolean * SOAP_FMAC6 soap_new_ns__echoBoolean(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoBoolean(struct soap*, struct ns__echoBoolean*);
SOAP_FMAC3 struct ns__echoBoolean * SOAP_FMAC4 soap_instantiate_ns__echoBoolean(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoBoolean(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoBooleanResponse
#define SOAP_TYPE_ns__echoBooleanResponse (87)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoBooleanResponse(struct soap*, struct ns__echoBooleanResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoBooleanResponse(struct soap*, const struct ns__echoBooleanResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoBooleanResponse(struct soap*, const struct ns__echoBooleanResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoBooleanResponse(struct soap*, const char*, int, const struct ns__echoBooleanResponse *, const char*);
SOAP_FMAC3 struct ns__echoBooleanResponse * SOAP_FMAC4 soap_get_ns__echoBooleanResponse(struct soap*, struct ns__echoBooleanResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoBooleanResponse * SOAP_FMAC4 soap_in_ns__echoBooleanResponse(struct soap*, const char*, struct ns__echoBooleanResponse *, const char*);
SOAP_FMAC5 struct ns__echoBooleanResponse * SOAP_FMAC6 soap_new_ns__echoBooleanResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoBooleanResponse(struct soap*, struct ns__echoBooleanResponse*);
SOAP_FMAC3 struct ns__echoBooleanResponse * SOAP_FMAC4 soap_instantiate_ns__echoBooleanResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoBooleanResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoDecimal
#define SOAP_TYPE_ns__echoDecimal (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoDecimal(struct soap*, struct ns__echoDecimal *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoDecimal(struct soap*, const struct ns__echoDecimal *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoDecimal(struct soap*, const struct ns__echoDecimal *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoDecimal(struct soap*, const char*, int, const struct ns__echoDecimal *, const char*);
SOAP_FMAC3 struct ns__echoDecimal * SOAP_FMAC4 soap_get_ns__echoDecimal(struct soap*, struct ns__echoDecimal *, const char*, const char*);
SOAP_FMAC3 struct ns__echoDecimal * SOAP_FMAC4 soap_in_ns__echoDecimal(struct soap*, const char*, struct ns__echoDecimal *, const char*);
SOAP_FMAC5 struct ns__echoDecimal * SOAP_FMAC6 soap_new_ns__echoDecimal(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoDecimal(struct soap*, struct ns__echoDecimal*);
SOAP_FMAC3 struct ns__echoDecimal * SOAP_FMAC4 soap_instantiate_ns__echoDecimal(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoDecimal(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoDecimalResponse
#define SOAP_TYPE_ns__echoDecimalResponse (81)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoDecimalResponse(struct soap*, struct ns__echoDecimalResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoDecimalResponse(struct soap*, const struct ns__echoDecimalResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoDecimalResponse(struct soap*, const struct ns__echoDecimalResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoDecimalResponse(struct soap*, const char*, int, const struct ns__echoDecimalResponse *, const char*);
SOAP_FMAC3 struct ns__echoDecimalResponse * SOAP_FMAC4 soap_get_ns__echoDecimalResponse(struct soap*, struct ns__echoDecimalResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoDecimalResponse * SOAP_FMAC4 soap_in_ns__echoDecimalResponse(struct soap*, const char*, struct ns__echoDecimalResponse *, const char*);
SOAP_FMAC5 struct ns__echoDecimalResponse * SOAP_FMAC6 soap_new_ns__echoDecimalResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoDecimalResponse(struct soap*, struct ns__echoDecimalResponse*);
SOAP_FMAC3 struct ns__echoDecimalResponse * SOAP_FMAC4 soap_instantiate_ns__echoDecimalResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoDecimalResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoHexBinary
#define SOAP_TYPE_ns__echoHexBinary (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoHexBinary(struct soap*, struct ns__echoHexBinary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoHexBinary(struct soap*, const struct ns__echoHexBinary *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoHexBinary(struct soap*, const struct ns__echoHexBinary *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoHexBinary(struct soap*, const char*, int, const struct ns__echoHexBinary *, const char*);
SOAP_FMAC3 struct ns__echoHexBinary * SOAP_FMAC4 soap_get_ns__echoHexBinary(struct soap*, struct ns__echoHexBinary *, const char*, const char*);
SOAP_FMAC3 struct ns__echoHexBinary * SOAP_FMAC4 soap_in_ns__echoHexBinary(struct soap*, const char*, struct ns__echoHexBinary *, const char*);
SOAP_FMAC5 struct ns__echoHexBinary * SOAP_FMAC6 soap_new_ns__echoHexBinary(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoHexBinary(struct soap*, struct ns__echoHexBinary*);
SOAP_FMAC3 struct ns__echoHexBinary * SOAP_FMAC4 soap_instantiate_ns__echoHexBinary(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoHexBinary(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoHexBinaryResponse
#define SOAP_TYPE_ns__echoHexBinaryResponse (76)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoHexBinaryResponse(struct soap*, struct ns__echoHexBinaryResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoHexBinaryResponse(struct soap*, const struct ns__echoHexBinaryResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoHexBinaryResponse(struct soap*, const struct ns__echoHexBinaryResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoHexBinaryResponse(struct soap*, const char*, int, const struct ns__echoHexBinaryResponse *, const char*);
SOAP_FMAC3 struct ns__echoHexBinaryResponse * SOAP_FMAC4 soap_get_ns__echoHexBinaryResponse(struct soap*, struct ns__echoHexBinaryResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoHexBinaryResponse * SOAP_FMAC4 soap_in_ns__echoHexBinaryResponse(struct soap*, const char*, struct ns__echoHexBinaryResponse *, const char*);
SOAP_FMAC5 struct ns__echoHexBinaryResponse * SOAP_FMAC6 soap_new_ns__echoHexBinaryResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoHexBinaryResponse(struct soap*, struct ns__echoHexBinaryResponse*);
SOAP_FMAC3 struct ns__echoHexBinaryResponse * SOAP_FMAC4 soap_instantiate_ns__echoHexBinaryResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoHexBinaryResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__hexBinary
#define SOAP_TYPE_xsd__hexBinary (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__hexBinary(struct soap*, struct xsd__hexBinary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__hexBinary(struct soap*, struct xsd__hexBinary const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__hexBinary(struct soap*, const struct xsd__hexBinary *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__hexBinary(struct soap*, const char*, int, const struct xsd__hexBinary *, const char*);
SOAP_FMAC3 struct xsd__hexBinary * SOAP_FMAC4 soap_get_xsd__hexBinary(struct soap*, struct xsd__hexBinary *, const char*, const char*);
SOAP_FMAC3 struct xsd__hexBinary * SOAP_FMAC4 soap_in_xsd__hexBinary(struct soap*, const char*, struct xsd__hexBinary *, const char*);
SOAP_FMAC5 struct xsd__hexBinary * SOAP_FMAC6 soap_new_xsd__hexBinary(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__hexBinary(struct soap*, struct xsd__hexBinary*);
SOAP_FMAC3 struct xsd__hexBinary * SOAP_FMAC4 soap_instantiate_xsd__hexBinary(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__hexBinary(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoDate
#define SOAP_TYPE_ns__echoDate (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoDate(struct soap*, struct ns__echoDate *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoDate(struct soap*, const struct ns__echoDate *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoDate(struct soap*, const struct ns__echoDate *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoDate(struct soap*, const char*, int, const struct ns__echoDate *, const char*);
SOAP_FMAC3 struct ns__echoDate * SOAP_FMAC4 soap_get_ns__echoDate(struct soap*, struct ns__echoDate *, const char*, const char*);
SOAP_FMAC3 struct ns__echoDate * SOAP_FMAC4 soap_in_ns__echoDate(struct soap*, const char*, struct ns__echoDate *, const char*);
SOAP_FMAC5 struct ns__echoDate * SOAP_FMAC6 soap_new_ns__echoDate(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoDate(struct soap*, struct ns__echoDate*);
SOAP_FMAC3 struct ns__echoDate * SOAP_FMAC4 soap_instantiate_ns__echoDate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoDate(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoDateResponse
#define SOAP_TYPE_ns__echoDateResponse (71)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoDateResponse(struct soap*, struct ns__echoDateResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoDateResponse(struct soap*, const struct ns__echoDateResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoDateResponse(struct soap*, const struct ns__echoDateResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoDateResponse(struct soap*, const char*, int, const struct ns__echoDateResponse *, const char*);
SOAP_FMAC3 struct ns__echoDateResponse * SOAP_FMAC4 soap_get_ns__echoDateResponse(struct soap*, struct ns__echoDateResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoDateResponse * SOAP_FMAC4 soap_in_ns__echoDateResponse(struct soap*, const char*, struct ns__echoDateResponse *, const char*);
SOAP_FMAC5 struct ns__echoDateResponse * SOAP_FMAC6 soap_new_ns__echoDateResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoDateResponse(struct soap*, struct ns__echoDateResponse*);
SOAP_FMAC3 struct ns__echoDateResponse * SOAP_FMAC4 soap_instantiate_ns__echoDateResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoDateResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoBase64
#define SOAP_TYPE_ns__echoBase64 (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoBase64(struct soap*, struct ns__echoBase64 *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoBase64(struct soap*, const struct ns__echoBase64 *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoBase64(struct soap*, const struct ns__echoBase64 *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoBase64(struct soap*, const char*, int, const struct ns__echoBase64 *, const char*);
SOAP_FMAC3 struct ns__echoBase64 * SOAP_FMAC4 soap_get_ns__echoBase64(struct soap*, struct ns__echoBase64 *, const char*, const char*);
SOAP_FMAC3 struct ns__echoBase64 * SOAP_FMAC4 soap_in_ns__echoBase64(struct soap*, const char*, struct ns__echoBase64 *, const char*);
SOAP_FMAC5 struct ns__echoBase64 * SOAP_FMAC6 soap_new_ns__echoBase64(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoBase64(struct soap*, struct ns__echoBase64*);
SOAP_FMAC3 struct ns__echoBase64 * SOAP_FMAC4 soap_instantiate_ns__echoBase64(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoBase64(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoBase64Response
#define SOAP_TYPE_ns__echoBase64Response (66)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoBase64Response(struct soap*, struct ns__echoBase64Response *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoBase64Response(struct soap*, const struct ns__echoBase64Response *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoBase64Response(struct soap*, const struct ns__echoBase64Response *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoBase64Response(struct soap*, const char*, int, const struct ns__echoBase64Response *, const char*);
SOAP_FMAC3 struct ns__echoBase64Response * SOAP_FMAC4 soap_get_ns__echoBase64Response(struct soap*, struct ns__echoBase64Response *, const char*, const char*);
SOAP_FMAC3 struct ns__echoBase64Response * SOAP_FMAC4 soap_in_ns__echoBase64Response(struct soap*, const char*, struct ns__echoBase64Response *, const char*);
SOAP_FMAC5 struct ns__echoBase64Response * SOAP_FMAC6 soap_new_ns__echoBase64Response(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoBase64Response(struct soap*, struct ns__echoBase64Response*);
SOAP_FMAC3 struct ns__echoBase64Response * SOAP_FMAC4 soap_instantiate_ns__echoBase64Response(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoBase64Response(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_xsd__base64Binary
#define SOAP_TYPE_xsd__base64Binary (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__base64Binary(struct soap*, struct xsd__base64Binary *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__base64Binary(struct soap*, struct xsd__base64Binary const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__base64Binary(struct soap*, const struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__base64Binary(struct soap*, const char*, int, const struct xsd__base64Binary *, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_get_xsd__base64Binary(struct soap*, struct xsd__base64Binary *, const char*, const char*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_in_xsd__base64Binary(struct soap*, const char*, struct xsd__base64Binary *, const char*);
SOAP_FMAC5 struct xsd__base64Binary * SOAP_FMAC6 soap_new_xsd__base64Binary(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_xsd__base64Binary(struct soap*, struct xsd__base64Binary*);
SOAP_FMAC3 struct xsd__base64Binary * SOAP_FMAC4 soap_instantiate_xsd__base64Binary(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_xsd__base64Binary(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoVoid
#define SOAP_TYPE_ns__echoVoid (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoVoid(struct soap*, struct ns__echoVoid *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoVoid(struct soap*, const struct ns__echoVoid *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoVoid(struct soap*, const struct ns__echoVoid *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoVoid(struct soap*, const char*, int, const struct ns__echoVoid *, const char*);
SOAP_FMAC3 struct ns__echoVoid * SOAP_FMAC4 soap_get_ns__echoVoid(struct soap*, struct ns__echoVoid *, const char*, const char*);
SOAP_FMAC3 struct ns__echoVoid * SOAP_FMAC4 soap_in_ns__echoVoid(struct soap*, const char*, struct ns__echoVoid *, const char*);
SOAP_FMAC5 struct ns__echoVoid * SOAP_FMAC6 soap_new_ns__echoVoid(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoVoid(struct soap*, struct ns__echoVoid*);
SOAP_FMAC3 struct ns__echoVoid * SOAP_FMAC4 soap_instantiate_ns__echoVoid(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoVoid(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoVoidResponse
#define SOAP_TYPE_ns__echoVoidResponse (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoVoidResponse(struct soap*, struct ns__echoVoidResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoVoidResponse(struct soap*, const struct ns__echoVoidResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoVoidResponse(struct soap*, const struct ns__echoVoidResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoVoidResponse(struct soap*, const char*, int, const struct ns__echoVoidResponse *, const char*);
SOAP_FMAC3 struct ns__echoVoidResponse * SOAP_FMAC4 soap_get_ns__echoVoidResponse(struct soap*, struct ns__echoVoidResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoVoidResponse * SOAP_FMAC4 soap_in_ns__echoVoidResponse(struct soap*, const char*, struct ns__echoVoidResponse *, const char*);
SOAP_FMAC5 struct ns__echoVoidResponse * SOAP_FMAC6 soap_new_ns__echoVoidResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoVoidResponse(struct soap*, struct ns__echoVoidResponse*);
SOAP_FMAC3 struct ns__echoVoidResponse * SOAP_FMAC4 soap_instantiate_ns__echoVoidResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoVoidResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoStructArray
#define SOAP_TYPE_ns__echoStructArray (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoStructArray(struct soap*, struct ns__echoStructArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoStructArray(struct soap*, const struct ns__echoStructArray *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoStructArray(struct soap*, const struct ns__echoStructArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoStructArray(struct soap*, const char*, int, const struct ns__echoStructArray *, const char*);
SOAP_FMAC3 struct ns__echoStructArray * SOAP_FMAC4 soap_get_ns__echoStructArray(struct soap*, struct ns__echoStructArray *, const char*, const char*);
SOAP_FMAC3 struct ns__echoStructArray * SOAP_FMAC4 soap_in_ns__echoStructArray(struct soap*, const char*, struct ns__echoStructArray *, const char*);
SOAP_FMAC5 struct ns__echoStructArray * SOAP_FMAC6 soap_new_ns__echoStructArray(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoStructArray(struct soap*, struct ns__echoStructArray*);
SOAP_FMAC3 struct ns__echoStructArray * SOAP_FMAC4 soap_instantiate_ns__echoStructArray(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoStructArray(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoStructArrayResponse
#define SOAP_TYPE_ns__echoStructArrayResponse (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoStructArrayResponse(struct soap*, struct ns__echoStructArrayResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoStructArrayResponse(struct soap*, const struct ns__echoStructArrayResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoStructArrayResponse(struct soap*, const struct ns__echoStructArrayResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoStructArrayResponse(struct soap*, const char*, int, const struct ns__echoStructArrayResponse *, const char*);
SOAP_FMAC3 struct ns__echoStructArrayResponse * SOAP_FMAC4 soap_get_ns__echoStructArrayResponse(struct soap*, struct ns__echoStructArrayResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoStructArrayResponse * SOAP_FMAC4 soap_in_ns__echoStructArrayResponse(struct soap*, const char*, struct ns__echoStructArrayResponse *, const char*);
SOAP_FMAC5 struct ns__echoStructArrayResponse * SOAP_FMAC6 soap_new_ns__echoStructArrayResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoStructArrayResponse(struct soap*, struct ns__echoStructArrayResponse*);
SOAP_FMAC3 struct ns__echoStructArrayResponse * SOAP_FMAC4 soap_instantiate_ns__echoStructArrayResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoStructArrayResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOfSOAPStruct
#define SOAP_TYPE_ArrayOfSOAPStruct (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfSOAPStruct(struct soap*, struct ArrayOfSOAPStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfSOAPStruct(struct soap*, struct ArrayOfSOAPStruct const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfSOAPStruct(struct soap*, const struct ArrayOfSOAPStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfSOAPStruct(struct soap*, const char*, int, const struct ArrayOfSOAPStruct *, const char*);
SOAP_FMAC3 struct ArrayOfSOAPStruct * SOAP_FMAC4 soap_get_ArrayOfSOAPStruct(struct soap*, struct ArrayOfSOAPStruct *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfSOAPStruct * SOAP_FMAC4 soap_in_ArrayOfSOAPStruct(struct soap*, const char*, struct ArrayOfSOAPStruct *, const char*);
SOAP_FMAC5 struct ArrayOfSOAPStruct * SOAP_FMAC6 soap_new_ArrayOfSOAPStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOfSOAPStruct(struct soap*, struct ArrayOfSOAPStruct*);
SOAP_FMAC3 struct ArrayOfSOAPStruct * SOAP_FMAC4 soap_instantiate_ArrayOfSOAPStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOfSOAPStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoStruct
#define SOAP_TYPE_ns__echoStruct (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoStruct(struct soap*, struct ns__echoStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoStruct(struct soap*, const struct ns__echoStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoStruct(struct soap*, const struct ns__echoStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoStruct(struct soap*, const char*, int, const struct ns__echoStruct *, const char*);
SOAP_FMAC3 struct ns__echoStruct * SOAP_FMAC4 soap_get_ns__echoStruct(struct soap*, struct ns__echoStruct *, const char*, const char*);
SOAP_FMAC3 struct ns__echoStruct * SOAP_FMAC4 soap_in_ns__echoStruct(struct soap*, const char*, struct ns__echoStruct *, const char*);
SOAP_FMAC5 struct ns__echoStruct * SOAP_FMAC6 soap_new_ns__echoStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoStruct(struct soap*, struct ns__echoStruct*);
SOAP_FMAC3 struct ns__echoStruct * SOAP_FMAC4 soap_instantiate_ns__echoStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoStructResponse
#define SOAP_TYPE_ns__echoStructResponse (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoStructResponse(struct soap*, struct ns__echoStructResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoStructResponse(struct soap*, const struct ns__echoStructResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoStructResponse(struct soap*, const struct ns__echoStructResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoStructResponse(struct soap*, const char*, int, const struct ns__echoStructResponse *, const char*);
SOAP_FMAC3 struct ns__echoStructResponse * SOAP_FMAC4 soap_get_ns__echoStructResponse(struct soap*, struct ns__echoStructResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoStructResponse * SOAP_FMAC4 soap_in_ns__echoStructResponse(struct soap*, const char*, struct ns__echoStructResponse *, const char*);
SOAP_FMAC5 struct ns__echoStructResponse * SOAP_FMAC6 soap_new_ns__echoStructResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoStructResponse(struct soap*, struct ns__echoStructResponse*);
SOAP_FMAC3 struct ns__echoStructResponse * SOAP_FMAC4 soap_instantiate_ns__echoStructResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoStructResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_s__SOAPStruct
#define SOAP_TYPE_s__SOAPStruct (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_s__SOAPStruct(struct soap*, struct s__SOAPStruct *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_s__SOAPStruct(struct soap*, const struct s__SOAPStruct *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_s__SOAPStruct(struct soap*, const struct s__SOAPStruct *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_s__SOAPStruct(struct soap*, const char*, int, const struct s__SOAPStruct *, const char*);
SOAP_FMAC3 struct s__SOAPStruct * SOAP_FMAC4 soap_get_s__SOAPStruct(struct soap*, struct s__SOAPStruct *, const char*, const char*);
SOAP_FMAC3 struct s__SOAPStruct * SOAP_FMAC4 soap_in_s__SOAPStruct(struct soap*, const char*, struct s__SOAPStruct *, const char*);
SOAP_FMAC5 struct s__SOAPStruct * SOAP_FMAC6 soap_new_s__SOAPStruct(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_s__SOAPStruct(struct soap*, struct s__SOAPStruct*);
SOAP_FMAC3 struct s__SOAPStruct * SOAP_FMAC4 soap_instantiate_s__SOAPStruct(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_s__SOAPStruct(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoFloatArray
#define SOAP_TYPE_ns__echoFloatArray (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoFloatArray(struct soap*, struct ns__echoFloatArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoFloatArray(struct soap*, const struct ns__echoFloatArray *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoFloatArray(struct soap*, const struct ns__echoFloatArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoFloatArray(struct soap*, const char*, int, const struct ns__echoFloatArray *, const char*);
SOAP_FMAC3 struct ns__echoFloatArray * SOAP_FMAC4 soap_get_ns__echoFloatArray(struct soap*, struct ns__echoFloatArray *, const char*, const char*);
SOAP_FMAC3 struct ns__echoFloatArray * SOAP_FMAC4 soap_in_ns__echoFloatArray(struct soap*, const char*, struct ns__echoFloatArray *, const char*);
SOAP_FMAC5 struct ns__echoFloatArray * SOAP_FMAC6 soap_new_ns__echoFloatArray(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoFloatArray(struct soap*, struct ns__echoFloatArray*);
SOAP_FMAC3 struct ns__echoFloatArray * SOAP_FMAC4 soap_instantiate_ns__echoFloatArray(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoFloatArray(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoFloatArrayResponse
#define SOAP_TYPE_ns__echoFloatArrayResponse (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoFloatArrayResponse(struct soap*, struct ns__echoFloatArrayResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoFloatArrayResponse(struct soap*, const struct ns__echoFloatArrayResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoFloatArrayResponse(struct soap*, const struct ns__echoFloatArrayResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoFloatArrayResponse(struct soap*, const char*, int, const struct ns__echoFloatArrayResponse *, const char*);
SOAP_FMAC3 struct ns__echoFloatArrayResponse * SOAP_FMAC4 soap_get_ns__echoFloatArrayResponse(struct soap*, struct ns__echoFloatArrayResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoFloatArrayResponse * SOAP_FMAC4 soap_in_ns__echoFloatArrayResponse(struct soap*, const char*, struct ns__echoFloatArrayResponse *, const char*);
SOAP_FMAC5 struct ns__echoFloatArrayResponse * SOAP_FMAC6 soap_new_ns__echoFloatArrayResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoFloatArrayResponse(struct soap*, struct ns__echoFloatArrayResponse*);
SOAP_FMAC3 struct ns__echoFloatArrayResponse * SOAP_FMAC4 soap_instantiate_ns__echoFloatArrayResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoFloatArrayResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOffloat
#define SOAP_TYPE_ArrayOffloat (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOffloat(struct soap*, struct ArrayOffloat *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOffloat(struct soap*, struct ArrayOffloat const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOffloat(struct soap*, const struct ArrayOffloat *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOffloat(struct soap*, const char*, int, const struct ArrayOffloat *, const char*);
SOAP_FMAC3 struct ArrayOffloat * SOAP_FMAC4 soap_get_ArrayOffloat(struct soap*, struct ArrayOffloat *, const char*, const char*);
SOAP_FMAC3 struct ArrayOffloat * SOAP_FMAC4 soap_in_ArrayOffloat(struct soap*, const char*, struct ArrayOffloat *, const char*);
SOAP_FMAC5 struct ArrayOffloat * SOAP_FMAC6 soap_new_ArrayOffloat(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOffloat(struct soap*, struct ArrayOffloat*);
SOAP_FMAC3 struct ArrayOffloat * SOAP_FMAC4 soap_instantiate_ArrayOffloat(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOffloat(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoFloat
#define SOAP_TYPE_ns__echoFloat (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoFloat(struct soap*, struct ns__echoFloat *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoFloat(struct soap*, const struct ns__echoFloat *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoFloat(struct soap*, const struct ns__echoFloat *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoFloat(struct soap*, const char*, int, const struct ns__echoFloat *, const char*);
SOAP_FMAC3 struct ns__echoFloat * SOAP_FMAC4 soap_get_ns__echoFloat(struct soap*, struct ns__echoFloat *, const char*, const char*);
SOAP_FMAC3 struct ns__echoFloat * SOAP_FMAC4 soap_in_ns__echoFloat(struct soap*, const char*, struct ns__echoFloat *, const char*);
SOAP_FMAC5 struct ns__echoFloat * SOAP_FMAC6 soap_new_ns__echoFloat(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoFloat(struct soap*, struct ns__echoFloat*);
SOAP_FMAC3 struct ns__echoFloat * SOAP_FMAC4 soap_instantiate_ns__echoFloat(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoFloat(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoFloatResponse
#define SOAP_TYPE_ns__echoFloatResponse (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoFloatResponse(struct soap*, struct ns__echoFloatResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoFloatResponse(struct soap*, const struct ns__echoFloatResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoFloatResponse(struct soap*, const struct ns__echoFloatResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoFloatResponse(struct soap*, const char*, int, const struct ns__echoFloatResponse *, const char*);
SOAP_FMAC3 struct ns__echoFloatResponse * SOAP_FMAC4 soap_get_ns__echoFloatResponse(struct soap*, struct ns__echoFloatResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoFloatResponse * SOAP_FMAC4 soap_in_ns__echoFloatResponse(struct soap*, const char*, struct ns__echoFloatResponse *, const char*);
SOAP_FMAC5 struct ns__echoFloatResponse * SOAP_FMAC6 soap_new_ns__echoFloatResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoFloatResponse(struct soap*, struct ns__echoFloatResponse*);
SOAP_FMAC3 struct ns__echoFloatResponse * SOAP_FMAC4 soap_instantiate_ns__echoFloatResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoFloatResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoIntegerArray
#define SOAP_TYPE_ns__echoIntegerArray (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoIntegerArray(struct soap*, struct ns__echoIntegerArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoIntegerArray(struct soap*, const struct ns__echoIntegerArray *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoIntegerArray(struct soap*, const struct ns__echoIntegerArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoIntegerArray(struct soap*, const char*, int, const struct ns__echoIntegerArray *, const char*);
SOAP_FMAC3 struct ns__echoIntegerArray * SOAP_FMAC4 soap_get_ns__echoIntegerArray(struct soap*, struct ns__echoIntegerArray *, const char*, const char*);
SOAP_FMAC3 struct ns__echoIntegerArray * SOAP_FMAC4 soap_in_ns__echoIntegerArray(struct soap*, const char*, struct ns__echoIntegerArray *, const char*);
SOAP_FMAC5 struct ns__echoIntegerArray * SOAP_FMAC6 soap_new_ns__echoIntegerArray(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoIntegerArray(struct soap*, struct ns__echoIntegerArray*);
SOAP_FMAC3 struct ns__echoIntegerArray * SOAP_FMAC4 soap_instantiate_ns__echoIntegerArray(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoIntegerArray(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoIntegerArrayResponse
#define SOAP_TYPE_ns__echoIntegerArrayResponse (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoIntegerArrayResponse(struct soap*, struct ns__echoIntegerArrayResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoIntegerArrayResponse(struct soap*, const struct ns__echoIntegerArrayResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoIntegerArrayResponse(struct soap*, const struct ns__echoIntegerArrayResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoIntegerArrayResponse(struct soap*, const char*, int, const struct ns__echoIntegerArrayResponse *, const char*);
SOAP_FMAC3 struct ns__echoIntegerArrayResponse * SOAP_FMAC4 soap_get_ns__echoIntegerArrayResponse(struct soap*, struct ns__echoIntegerArrayResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoIntegerArrayResponse * SOAP_FMAC4 soap_in_ns__echoIntegerArrayResponse(struct soap*, const char*, struct ns__echoIntegerArrayResponse *, const char*);
SOAP_FMAC5 struct ns__echoIntegerArrayResponse * SOAP_FMAC6 soap_new_ns__echoIntegerArrayResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoIntegerArrayResponse(struct soap*, struct ns__echoIntegerArrayResponse*);
SOAP_FMAC3 struct ns__echoIntegerArrayResponse * SOAP_FMAC4 soap_instantiate_ns__echoIntegerArrayResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoIntegerArrayResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOfint
#define SOAP_TYPE_ArrayOfint (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfint(struct soap*, struct ArrayOfint *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfint(struct soap*, struct ArrayOfint const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfint(struct soap*, const struct ArrayOfint *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfint(struct soap*, const char*, int, const struct ArrayOfint *, const char*);
SOAP_FMAC3 struct ArrayOfint * SOAP_FMAC4 soap_get_ArrayOfint(struct soap*, struct ArrayOfint *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfint * SOAP_FMAC4 soap_in_ArrayOfint(struct soap*, const char*, struct ArrayOfint *, const char*);
SOAP_FMAC5 struct ArrayOfint * SOAP_FMAC6 soap_new_ArrayOfint(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOfint(struct soap*, struct ArrayOfint*);
SOAP_FMAC3 struct ArrayOfint * SOAP_FMAC4 soap_instantiate_ArrayOfint(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOfint(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoInteger
#define SOAP_TYPE_ns__echoInteger (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoInteger(struct soap*, struct ns__echoInteger *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoInteger(struct soap*, const struct ns__echoInteger *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoInteger(struct soap*, const struct ns__echoInteger *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoInteger(struct soap*, const char*, int, const struct ns__echoInteger *, const char*);
SOAP_FMAC3 struct ns__echoInteger * SOAP_FMAC4 soap_get_ns__echoInteger(struct soap*, struct ns__echoInteger *, const char*, const char*);
SOAP_FMAC3 struct ns__echoInteger * SOAP_FMAC4 soap_in_ns__echoInteger(struct soap*, const char*, struct ns__echoInteger *, const char*);
SOAP_FMAC5 struct ns__echoInteger * SOAP_FMAC6 soap_new_ns__echoInteger(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoInteger(struct soap*, struct ns__echoInteger*);
SOAP_FMAC3 struct ns__echoInteger * SOAP_FMAC4 soap_instantiate_ns__echoInteger(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoInteger(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoIntegerResponse
#define SOAP_TYPE_ns__echoIntegerResponse (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoIntegerResponse(struct soap*, struct ns__echoIntegerResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoIntegerResponse(struct soap*, const struct ns__echoIntegerResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoIntegerResponse(struct soap*, const struct ns__echoIntegerResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoIntegerResponse(struct soap*, const char*, int, const struct ns__echoIntegerResponse *, const char*);
SOAP_FMAC3 struct ns__echoIntegerResponse * SOAP_FMAC4 soap_get_ns__echoIntegerResponse(struct soap*, struct ns__echoIntegerResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoIntegerResponse * SOAP_FMAC4 soap_in_ns__echoIntegerResponse(struct soap*, const char*, struct ns__echoIntegerResponse *, const char*);
SOAP_FMAC5 struct ns__echoIntegerResponse * SOAP_FMAC6 soap_new_ns__echoIntegerResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoIntegerResponse(struct soap*, struct ns__echoIntegerResponse*);
SOAP_FMAC3 struct ns__echoIntegerResponse * SOAP_FMAC4 soap_instantiate_ns__echoIntegerResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoIntegerResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoStringArray
#define SOAP_TYPE_ns__echoStringArray (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoStringArray(struct soap*, struct ns__echoStringArray *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoStringArray(struct soap*, const struct ns__echoStringArray *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoStringArray(struct soap*, const struct ns__echoStringArray *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoStringArray(struct soap*, const char*, int, const struct ns__echoStringArray *, const char*);
SOAP_FMAC3 struct ns__echoStringArray * SOAP_FMAC4 soap_get_ns__echoStringArray(struct soap*, struct ns__echoStringArray *, const char*, const char*);
SOAP_FMAC3 struct ns__echoStringArray * SOAP_FMAC4 soap_in_ns__echoStringArray(struct soap*, const char*, struct ns__echoStringArray *, const char*);
SOAP_FMAC5 struct ns__echoStringArray * SOAP_FMAC6 soap_new_ns__echoStringArray(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoStringArray(struct soap*, struct ns__echoStringArray*);
SOAP_FMAC3 struct ns__echoStringArray * SOAP_FMAC4 soap_instantiate_ns__echoStringArray(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoStringArray(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoStringArrayResponse
#define SOAP_TYPE_ns__echoStringArrayResponse (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoStringArrayResponse(struct soap*, struct ns__echoStringArrayResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoStringArrayResponse(struct soap*, const struct ns__echoStringArrayResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoStringArrayResponse(struct soap*, const struct ns__echoStringArrayResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoStringArrayResponse(struct soap*, const char*, int, const struct ns__echoStringArrayResponse *, const char*);
SOAP_FMAC3 struct ns__echoStringArrayResponse * SOAP_FMAC4 soap_get_ns__echoStringArrayResponse(struct soap*, struct ns__echoStringArrayResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoStringArrayResponse * SOAP_FMAC4 soap_in_ns__echoStringArrayResponse(struct soap*, const char*, struct ns__echoStringArrayResponse *, const char*);
SOAP_FMAC5 struct ns__echoStringArrayResponse * SOAP_FMAC6 soap_new_ns__echoStringArrayResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoStringArrayResponse(struct soap*, struct ns__echoStringArrayResponse*);
SOAP_FMAC3 struct ns__echoStringArrayResponse * SOAP_FMAC4 soap_instantiate_ns__echoStringArrayResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoStringArrayResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ArrayOfstring
#define SOAP_TYPE_ArrayOfstring (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfstring(struct soap*, struct ArrayOfstring *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfstring(struct soap*, struct ArrayOfstring const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfstring(struct soap*, const struct ArrayOfstring *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfstring(struct soap*, const char*, int, const struct ArrayOfstring *, const char*);
SOAP_FMAC3 struct ArrayOfstring * SOAP_FMAC4 soap_get_ArrayOfstring(struct soap*, struct ArrayOfstring *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfstring * SOAP_FMAC4 soap_in_ArrayOfstring(struct soap*, const char*, struct ArrayOfstring *, const char*);
SOAP_FMAC5 struct ArrayOfstring * SOAP_FMAC6 soap_new_ArrayOfstring(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ArrayOfstring(struct soap*, struct ArrayOfstring*);
SOAP_FMAC3 struct ArrayOfstring * SOAP_FMAC4 soap_instantiate_ArrayOfstring(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ArrayOfstring(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoString
#define SOAP_TYPE_ns__echoString (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoString(struct soap*, struct ns__echoString *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoString(struct soap*, const struct ns__echoString *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoString(struct soap*, const struct ns__echoString *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoString(struct soap*, const char*, int, const struct ns__echoString *, const char*);
SOAP_FMAC3 struct ns__echoString * SOAP_FMAC4 soap_get_ns__echoString(struct soap*, struct ns__echoString *, const char*, const char*);
SOAP_FMAC3 struct ns__echoString * SOAP_FMAC4 soap_in_ns__echoString(struct soap*, const char*, struct ns__echoString *, const char*);
SOAP_FMAC5 struct ns__echoString * SOAP_FMAC6 soap_new_ns__echoString(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoString(struct soap*, struct ns__echoString*);
SOAP_FMAC3 struct ns__echoString * SOAP_FMAC4 soap_instantiate_ns__echoString(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoString(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns__echoStringResponse
#define SOAP_TYPE_ns__echoStringResponse (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns__echoStringResponse(struct soap*, struct ns__echoStringResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns__echoStringResponse(struct soap*, const struct ns__echoStringResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns__echoStringResponse(struct soap*, const struct ns__echoStringResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns__echoStringResponse(struct soap*, const char*, int, const struct ns__echoStringResponse *, const char*);
SOAP_FMAC3 struct ns__echoStringResponse * SOAP_FMAC4 soap_get_ns__echoStringResponse(struct soap*, struct ns__echoStringResponse *, const char*, const char*);
SOAP_FMAC3 struct ns__echoStringResponse * SOAP_FMAC4 soap_in_ns__echoStringResponse(struct soap*, const char*, struct ns__echoStringResponse *, const char*);
SOAP_FMAC5 struct ns__echoStringResponse * SOAP_FMAC6 soap_new_ns__echoStringResponse(struct soap*, int);
SOAP_FMAC5 void SOAP_FMAC6 soap_delete_ns__echoStringResponse(struct soap*, struct ns__echoStringResponse*);
SOAP_FMAC3 struct ns__echoStringResponse * SOAP_FMAC4 soap_instantiate_ns__echoStringResponse(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns__echoStringResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (126)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (125)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (119)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_xsd__decimal
#define SOAP_TYPE_xsd__decimal (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__decimal(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__decimal(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__decimal(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__decimal(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__decimal(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__decimal(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_xsd__dateTime
#define SOAP_TYPE_xsd__dateTime (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__dateTime(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__dateTime(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__dateTime(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__dateTime(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__dateTime(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__dateTime(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_PointerTounsignedByte
#define SOAP_TYPE_PointerTounsignedByte (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTounsignedByte(struct soap*, unsigned char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTounsignedByte(struct soap*, unsigned char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTounsignedByte(struct soap*, const char *, int, unsigned char *const*, const char *);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_get_PointerTounsignedByte(struct soap*, unsigned char **, const char*, const char*);
SOAP_FMAC3 unsigned char ** SOAP_FMAC4 soap_in_PointerTounsignedByte(struct soap*, const char*, unsigned char **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTos__SOAPStruct
#define SOAP_TYPE_PointerToPointerTos__SOAPStruct (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTos__SOAPStruct(struct soap*, struct s__SOAPStruct **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTos__SOAPStruct(struct soap*, struct s__SOAPStruct **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTos__SOAPStruct(struct soap*, const char *, int, struct s__SOAPStruct **const*, const char *);
SOAP_FMAC3 struct s__SOAPStruct *** SOAP_FMAC4 soap_get_PointerToPointerTos__SOAPStruct(struct soap*, struct s__SOAPStruct ***, const char*, const char*);
SOAP_FMAC3 struct s__SOAPStruct *** SOAP_FMAC4 soap_in_PointerToPointerTos__SOAPStruct(struct soap*, const char*, struct s__SOAPStruct ***, const char*);

#ifndef SOAP_TYPE_PointerTos__SOAPStruct
#define SOAP_TYPE_PointerTos__SOAPStruct (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTos__SOAPStruct(struct soap*, struct s__SOAPStruct *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTos__SOAPStruct(struct soap*, struct s__SOAPStruct *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTos__SOAPStruct(struct soap*, const char *, int, struct s__SOAPStruct *const*, const char *);
SOAP_FMAC3 struct s__SOAPStruct ** SOAP_FMAC4 soap_get_PointerTos__SOAPStruct(struct soap*, struct s__SOAPStruct **, const char*, const char*);
SOAP_FMAC3 struct s__SOAPStruct ** SOAP_FMAC4 soap_in_PointerTos__SOAPStruct(struct soap*, const char*, struct s__SOAPStruct **, const char*);

#ifndef SOAP_TYPE_PointerToPointerToxsd__float
#define SOAP_TYPE_PointerToPointerToxsd__float (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerToxsd__float(struct soap*, float **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerToxsd__float(struct soap*, float **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerToxsd__float(struct soap*, const char *, int, float **const*, const char *);
SOAP_FMAC3 float *** SOAP_FMAC4 soap_get_PointerToPointerToxsd__float(struct soap*, float ***, const char*, const char*);
SOAP_FMAC3 float *** SOAP_FMAC4 soap_in_PointerToPointerToxsd__float(struct soap*, const char*, float ***, const char*);

#ifndef SOAP_TYPE_PointerToxsd__float
#define SOAP_TYPE_PointerToxsd__float (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__float(struct soap*, float *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__float(struct soap*, float *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__float(struct soap*, const char *, int, float *const*, const char *);
SOAP_FMAC3 float ** SOAP_FMAC4 soap_get_PointerToxsd__float(struct soap*, float **, const char*, const char*);
SOAP_FMAC3 float ** SOAP_FMAC4 soap_in_PointerToxsd__float(struct soap*, const char*, float **, const char*);

#ifndef SOAP_TYPE_PointerToPointerToxsd__int
#define SOAP_TYPE_PointerToPointerToxsd__int (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerToxsd__int(struct soap*, long **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerToxsd__int(struct soap*, long **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerToxsd__int(struct soap*, const char *, int, long **const*, const char *);
SOAP_FMAC3 long *** SOAP_FMAC4 soap_get_PointerToPointerToxsd__int(struct soap*, long ***, const char*, const char*);
SOAP_FMAC3 long *** SOAP_FMAC4 soap_in_PointerToPointerToxsd__int(struct soap*, const char*, long ***, const char*);

#ifndef SOAP_TYPE_PointerToxsd__int
#define SOAP_TYPE_PointerToxsd__int (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__int(struct soap*, long *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__int(struct soap*, long *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__int(struct soap*, const char *, int, long *const*, const char *);
SOAP_FMAC3 long ** SOAP_FMAC4 soap_get_PointerToxsd__int(struct soap*, long **, const char*, const char*);
SOAP_FMAC3 long ** SOAP_FMAC4 soap_in_PointerToxsd__int(struct soap*, const char*, long **, const char*);

#ifndef SOAP_TYPE_PointerToxsd__string
#define SOAP_TYPE_PointerToxsd__string (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToxsd__string(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToxsd__string(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToxsd__string(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerToxsd__string(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerToxsd__string(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE_xsd__string
#define SOAP_TYPE_xsd__string (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_xsd__string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_xsd__string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_xsd__string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default__QName(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_Array2Ofint
#define SOAP_TYPE_Array2Ofint (98)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_Array2Ofint(struct soap*, int[2]);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_Array2Ofint(struct soap*, int const[2]);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_Array2Ofint(struct soap*, int const[2], const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_Array2Ofint(struct soap*, const char*, int, int const[2], const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_Array2Ofint(struct soap*, int[2], const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_Array2Ofint(struct soap*, const char*, int[2], const char*);

#endif

/* End of soapH.h */
